-- =====================================================================
-- MIGRATION 001 — GARANTIAS LOCATÍCIAS
-- =====================================================================
-- Substitui os "ganchos" de garantia que existiam em `contratos`
-- (tipo_garantia + valor_caucao) por um modelo completo:
--
--   garantias (supertipo)
--     ├── garantia_caucao         (1:1)
--     ├── garantia_fiadores       (1:N)
--     └── garantia_seguro_fianca  (1:1)
--
-- Base legal (resumo — validar com o jurídico):
--   Lei 8.245/91 (Lei do Inquilinato)
--     art. 37, § único → UMA única modalidade de garantia por contrato
--     art. 38, §1º     → caução em bem móvel: registro em RTD;
--                        em bem imóvel: averbação na matrícula
--     art. 38, §2º     → caução em dinheiro: máx. 3 aluguéis, em caderneta
--                        de poupança, rendimentos revertem ao locatário
--     art. 39          → a garantia se estende até a DEVOLUÇÃO EFETIVA do imóvel
--     art. 40          → substituição de garantia / exoneração do fiador
--     art. 40, X       → fiador exonerado responde por mais 120 dias
--     art. 41          → seguro fiança cobre a totalidade das obrigações
--   Código Civil
--     art. 1.647, III  → fiança de pessoa casada exige outorga conjugal
--                        (salvo separação absoluta), sob pena de anulabilidade
--   Lei 10.192/2001    → reajuste com periodicidade mínima anual
--
-- SEGURO: todas as tabelas de contrato estavam VAZIAS quando esta migration
-- foi escrita, portanto os DROPs abaixo não descartam dados.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Ajustes em `contratos`
-- ---------------------------------------------------------------------

-- tipo_garantia e valor_caucao viram derivados da garantia ATIVA.
-- Ausência de garantia ATIVA = locação sem garantia (art. 42).
ALTER TABLE public.contratos DROP CONSTRAINT IF EXISTS contratos_garantia_chk;
ALTER TABLE public.contratos DROP COLUMN IF EXISTS tipo_garantia;
ALTER TABLE public.contratos DROP COLUMN IF EXISTS valor_caucao;

-- Art. 39: a garantia acompanha a locação até a devolução efetiva do imóvel,
-- que pode ser depois de data_fim (contrato prorrogado por prazo indeterminado).
ALTER TABLE public.contratos ADD COLUMN IF NOT EXISTS data_devolucao_imovel date NULL;

-- Lei 10.192/2001: reajuste não pode ter periodicidade inferior a 12 meses.
ALTER TABLE public.contratos DROP CONSTRAINT IF EXISTS contratos_reajuste_chk;
ALTER TABLE public.contratos
  ADD CONSTRAINT contratos_reajuste_chk CHECK (periodicidade_reajuste_meses >= 12);

-- ---------------------------------------------------------------------
-- 2. `garantias` — supertipo
-- ---------------------------------------------------------------------

CREATE TABLE public.garantias (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id         bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  tipo                text   NOT NULL,                   -- CAUCAO | FIADOR | SEGURO_FIANCA
  status              text   NOT NULL DEFAULT 'ATIVA',   -- ATIVA | SUBSTITUIDA | ENCERRADA
  data_inicio         date   NOT NULL DEFAULT CURRENT_DATE,
  data_fim            date   NULL,                       -- preenchida ao substituir/encerrar
  motivo_substituicao text   NULL,                       -- art. 40
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT garantias_tipo_chk   CHECK (tipo IN ('CAUCAO','FIADOR','SEGURO_FIANCA')),
  CONSTRAINT garantias_status_chk CHECK (status IN ('ATIVA','SUBSTITUIDA','ENCERRADA')),
  CONSTRAINT garantias_datas_chk  CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

-- Art. 37, § único: é VEDADA mais de uma modalidade de garantia no mesmo
-- contrato (e exigir duas é contravenção penal — art. 43, II).
-- O índice parcial faz o próprio banco impedir isso.
CREATE UNIQUE INDEX uq_garantia_ativa_por_contrato
  ON public.garantias (contrato_id) WHERE status = 'ATIVA';

CREATE INDEX idx_garantias_contrato ON public.garantias (contrato_id);

CREATE TRIGGER trg_garantias_updated BEFORE UPDATE ON public.garantias
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 3. `garantia_caucao` (1:1)
-- ---------------------------------------------------------------------

CREATE TABLE public.garantia_caucao (
  garantia_id       bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  modalidade        text NOT NULL,          -- DINHEIRO | BEM_MOVEL | BEM_IMOVEL | TITULOS (art. 38)
  valor             numeric(12,2) NULL,     -- obrigatório quando DINHEIRO

  -- Caução em dinheiro → caderneta de poupança (art. 38, §2º)
  banco             text NULL,
  agencia           text NULL,
  conta_poupanca    text NULL,
  data_deposito     date NULL,

  -- Caução em bens (art. 38, §1º)
  descricao_bem     text NULL,
  registro_cartorio text NULL,              -- RTD (móvel) ou averbação na matrícula (imóvel)

  -- Devolução ao final da locação (rendimentos revertem ao locatário — art. 38, §2º)
  valor_devolvido   numeric(12,2) NULL,
  valor_retido      numeric(12,2) NULL,
  motivo_retencao   text NULL,
  data_devolucao    date NULL,

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT caucao_modalidade_chk CHECK (modalidade IN ('DINHEIRO','BEM_MOVEL','BEM_IMOVEL','TITULOS')),
  CONSTRAINT caucao_dinheiro_chk   CHECK (modalidade <> 'DINHEIRO' OR valor IS NOT NULL),
  CONSTRAINT caucao_bem_chk        CHECK (modalidade = 'DINHEIRO' OR descricao_bem IS NOT NULL),
  CONSTRAINT caucao_valores_chk    CHECK (
    (valor           IS NULL OR valor           >= 0) AND
    (valor_devolvido IS NULL OR valor_devolvido >= 0) AND
    (valor_retido    IS NULL OR valor_retido    >= 0)
  ),
  CONSTRAINT caucao_retencao_chk   CHECK (
    valor_retido IS NULL OR valor_retido = 0 OR motivo_retencao IS NOT NULL
  )
);

CREATE TRIGGER trg_garantia_caucao_updated BEFORE UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Art. 38, §2º: a caução EM DINHEIRO não pode exceder 3 meses de aluguel.
-- É uma regra cross-table (garantia_caucao → garantias → contratos), então não
-- cabe num CHECK. O service também valida (mensagem amigável); este trigger é a
-- rede de segurança no banco, porque o excesso torna a cláusula nula.
CREATE OR REPLACE FUNCTION valida_caucao_dinheiro()
RETURNS TRIGGER AS $$
DECLARE
  v_aluguel numeric(12,2);
BEGIN
  IF NEW.modalidade = 'DINHEIRO' THEN
    SELECT c.valor_aluguel
      INTO v_aluguel
      FROM public.garantias g
      JOIN public.contratos c ON c.id = g.contrato_id
     WHERE g.id = NEW.garantia_id;

    IF v_aluguel IS NOT NULL AND NEW.valor > (3 * v_aluguel) THEN
      RAISE EXCEPTION
        'Caucao em dinheiro nao pode exceder 3 alugueis (Lei 8.245/91, art. 38, §2º). Maximo: %, informado: %',
        (3 * v_aluguel), NEW.valor
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_caucao_limite_legal
  BEFORE INSERT OR UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION valida_caucao_dinheiro();

-- ---------------------------------------------------------------------
-- 4. `garantia_fiadores` (1:N) — substitui `contrato_fiadores`
-- ---------------------------------------------------------------------

DROP TABLE IF EXISTS public.contrato_fiadores;

CREATE TABLE public.garantia_fiadores (
  garantia_id                 bigint NOT NULL REFERENCES public.garantias(id) ON DELETE CASCADE,
  usuario_id                  bigint NOT NULL REFERENCES public.usuarios(id)  ON DELETE RESTRICT,

  -- Capacidade financeira (praxe de mercado: renda >= 3x o aluguel)
  renda_comprovada            numeric(12,2) NULL,
  comprovante_renda_key       text NULL,   -- chave do objeto no S3 (bucket privado) — nunca URL pública

  -- Imóvel dado em garantia. O bem de família do fiador é penhorável
  -- (Lei 8.009/90, art. 3º, VII). Não vira linha em `imoveis`: aquela tabela
  -- é de imóvel PARA LOCAÇÃO (valor_aluguel_referencia, status DISPONIVEL...).
  imovel_garantia_endereco_id bigint NULL REFERENCES public.enderecos(id) ON DELETE SET NULL,
  imovel_garantia_matricula   text NULL,
  imovel_garantia_quitado     boolean NULL,

  -- Outorga conjugal (CC art. 1.647, III): sem ela, a fiança prestada por
  -- pessoa casada é ANULÁVEL — exceto no regime de separação absoluta.
  estado_civil                text NULL,   -- SOLTEIRO | CASADO | DIVORCIADO | VIUVO | UNIAO_ESTAVEL
  regime_bens                 text NULL,   -- COMUNHAO_PARCIAL | COMUNHAO_UNIVERSAL | SEPARACAO_ABSOLUTA | PARTICIPACAO_FINAL
  conjuge_nome                text NULL,
  conjuge_documento           text NULL,
  outorga_conjugal            boolean NOT NULL DEFAULT false,

  -- Exoneração (Lei 8.245/91, art. 40, X): o fiador segue responsável
  -- por 120 dias após a notificação ao locador.
  status                      text NOT NULL DEFAULT 'ATIVO',   -- ATIVO | EXONERADO
  data_notificacao_exoneracao date NULL,
  data_fim_responsabilidade   date NULL,                       -- notificação + 120 dias

  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (garantia_id, usuario_id),

  CONSTRAINT fiador_status_chk       CHECK (status IN ('ATIVO','EXONERADO')),
  CONSTRAINT fiador_estado_civil_chk CHECK (
    estado_civil IS NULL OR
    estado_civil IN ('SOLTEIRO','CASADO','DIVORCIADO','VIUVO','UNIAO_ESTAVEL')
  ),
  CONSTRAINT fiador_regime_bens_chk  CHECK (
    regime_bens IS NULL OR
    regime_bens IN ('COMUNHAO_PARCIAL','COMUNHAO_UNIVERSAL','SEPARACAO_ABSOLUTA','PARTICIPACAO_FINAL')
  ),
  CONSTRAINT fiador_renda_chk        CHECK (renda_comprovada IS NULL OR renda_comprovada >= 0),
  -- CC art. 1.647, III: casado (fora da separação absoluta) exige outorga do cônjuge.
  CONSTRAINT fiador_outorga_chk      CHECK (
    estado_civil IS DISTINCT FROM 'CASADO'
    OR regime_bens = 'SEPARACAO_ABSOLUTA'
    OR outorga_conjugal = true
  ),
  -- Art. 40, X: exonerado precisa da data de notificação e do fim dos 120 dias.
  CONSTRAINT fiador_exoneracao_chk   CHECK (
    status <> 'EXONERADO'
    OR (data_notificacao_exoneracao IS NOT NULL AND data_fim_responsabilidade IS NOT NULL)
  )
);

CREATE INDEX idx_garantia_fiador_usuario ON public.garantia_fiadores (usuario_id);

CREATE TRIGGER trg_garantia_fiadores_updated BEFORE UPDATE ON public.garantia_fiadores
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 5. `garantia_seguro_fianca` (1:1)
-- ---------------------------------------------------------------------
-- A análise de crédito e o sinistro rodam na SEGURADORA, fora deste sistema.
-- Aqui só se registra que a apólice existe, foi aprovada e está vigente.

CREATE TABLE public.garantia_seguro_fianca (
  garantia_id          bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  seguradora           text NOT NULL,
  numero_apolice       text NOT NULL,
  vigencia_inicio      date NOT NULL,
  vigencia_fim         date NOT NULL,
  valor_cobertura      numeric(12,2) NOT NULL,   -- art. 41: totalidade das obrigações do locatário
  valor_premio         numeric(12,2) NULL,       -- o que o inquilino paga à seguradora
  periodicidade_premio text NULL,                -- MENSAL | ANUAL
  status_aprovacao     text NOT NULL DEFAULT 'PENDENTE',  -- PENDENTE | APROVADA | REJEITADA
  apolice_key          text NULL,                -- PDF da apólice no S3 (bucket privado)

  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT seguro_status_chk        CHECK (status_aprovacao IN ('PENDENTE','APROVADA','REJEITADA')),
  CONSTRAINT seguro_periodicidade_chk CHECK (periodicidade_premio IS NULL OR periodicidade_premio IN ('MENSAL','ANUAL')),
  CONSTRAINT seguro_vigencia_chk      CHECK (vigencia_fim > vigencia_inicio),
  CONSTRAINT seguro_valores_chk       CHECK (
    valor_cobertura >= 0 AND (valor_premio IS NULL OR valor_premio >= 0)
  ),
  CONSTRAINT uq_seguro_apolice        UNIQUE (seguradora, numero_apolice)
);

CREATE TRIGGER trg_garantia_seguro_updated BEFORE UPDATE ON public.garantia_seguro_fianca
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 6. Limpeza — endereços órfãos (sem usuário e sem imóvel apontando)
-- ---------------------------------------------------------------------

DELETE FROM public.enderecos e
 WHERE NOT EXISTS (SELECT 1 FROM public.usuarios u WHERE u.endereco_id = e.id)
   AND NOT EXISTS (SELECT 1 FROM public.imoveis  i WHERE i.endereco_id = e.id)
   AND NOT EXISTS (
     SELECT 1 FROM public.garantia_fiadores f WHERE f.imovel_garantia_endereco_id = e.id
   );

COMMIT;
