-- =====================================================================
-- MIGRATION 007 — GESTÃO DOCUMENTAL, CAUÇÃO PIX E BAIXAS MANUAIS
-- =====================================================================

BEGIN;

ALTER TABLE public.imoveis
  ADD COLUMN IF NOT EXISTS numero_referencia text NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_imoveis_numero_referencia
  ON public.imoveis (numero_referencia)
  WHERE numero_referencia IS NOT NULL;

ALTER TABLE public.contratos
  ADD COLUMN IF NOT EXISTS migrado boolean NOT NULL DEFAULT false;

ALTER TABLE public.pagamentos
  ADD COLUMN IF NOT EXISTS origem text NOT NULL DEFAULT 'GATEWAY',
  ADD COLUMN IF NOT EXISTS comprovante_key text NULL;
ALTER TABLE public.pagamentos DROP CONSTRAINT IF EXISTS pagamentos_origem_chk;
ALTER TABLE public.pagamentos
  ADD CONSTRAINT pagamentos_origem_chk
  CHECK (origem IN ('GATEWAY','PRESENCIAL','MIGRACAO'));

ALTER TABLE public.garantia_fiadores
  ADD COLUMN IF NOT EXISTS certidao_imovel_key text NULL;

ALTER TABLE public.garantia_caucao
  ADD COLUMN IF NOT EXISTS status_pagamento text NOT NULL DEFAULT 'PENDENTE',
  ADD COLUMN IF NOT EXISTS pago_em timestamptz NULL,
  ADD COLUMN IF NOT EXISTS analisado_por bigint NULL
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS analisado_em timestamptz NULL;
ALTER TABLE public.garantia_caucao
  DROP CONSTRAINT IF EXISTS garantia_caucao_status_pagamento_chk;
ALTER TABLE public.garantia_caucao
  ADD CONSTRAINT garantia_caucao_status_pagamento_chk CHECK (
    status_pagamento IN ('PENDENTE','EM_ANALISE','PAGO','REJEITADO')
  );

CREATE TABLE IF NOT EXISTS public.caucao_cobrancas (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garantia_id           bigint NOT NULL UNIQUE
    REFERENCES public.garantias(id) ON DELETE CASCADE,
  gateway               text NOT NULL,
  external_payment_id   text NOT NULL,
  external_reference    text NOT NULL UNIQUE,
  qr_code_pix           text NULL,
  copia_cola_pix        text NULL,
  url_fatura            text NULL,
  valor                 numeric(12,2) NOT NULL,
  status_gateway        text NULL,
  ativa                 boolean NOT NULL DEFAULT true,
  raw_json              jsonb NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT caucao_cobrancas_valor_chk CHECK (valor > 0),
  CONSTRAINT caucao_cobrancas_gateway_external_key
    UNIQUE (gateway, external_payment_id)
);
CREATE INDEX IF NOT EXISTS idx_caucao_cobrancas_ativa
  ON public.caucao_cobrancas (ativa, garantia_id);

CREATE TABLE IF NOT EXISTS public.cliente_documentos (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id            bigint NOT NULL
    REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo                  text NOT NULL,
  nome_arquivo          text NOT NULL,
  s3_key                text NOT NULL UNIQUE,
  content_type          text NOT NULL,
  tamanho_bytes         bigint NULL,
  status                text NOT NULL DEFAULT 'PENDENTE',
  observacao_analise    text NULL,
  enviado_por           bigint NULL
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  analisado_por         bigint NULL
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  analisado_em          timestamptz NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cliente_documentos_tipo_chk CHECK (
    tipo IN (
      'CPF','COMPROVANTE_RENDA','SEGUNDO_TITULAR',
      'COMPROVANTE_RESIDENCIA_ANTERIOR','OUTRO'
    )
  ),
  CONSTRAINT cliente_documentos_status_chk CHECK (
    status IN ('PENDENTE','EM_ANALISE','APROVADO','REPROVADO')
  ),
  CONSTRAINT cliente_documentos_tamanho_chk CHECK (
    tamanho_bytes IS NULL OR tamanho_bytes BETWEEN 1 AND 10485760
  )
);
CREATE INDEX IF NOT EXISTS idx_cliente_documentos_usuario_historico
  ON public.cliente_documentos (usuario_id, tipo, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cliente_documentos_status
  ON public.cliente_documentos (status, created_at);

CREATE TABLE IF NOT EXISTS public.notificacoes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id            bigint NOT NULL
    REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo                  text NOT NULL,
  titulo                text NOT NULL,
  mensagem              text NOT NULL,
  referencia_tipo       text NULL,
  referencia_id         bigint NULL,
  lida_em               timestamptz NULL,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notificacoes_usuario
  ON public.notificacoes (usuario_id, lida_em, created_at DESC);

CREATE TABLE IF NOT EXISTS public.baixas_manuais (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id            bigint NOT NULL UNIQUE
    REFERENCES public.parcelas(id) ON DELETE RESTRICT,
  gateway_cobranca_id   bigint NOT NULL
    REFERENCES public.gateway_cobrancas(id) ON DELETE RESTRICT,
  solicitado_por        bigint NULL
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  valor_pago            numeric(12,2) NOT NULL,
  data_pagamento        date NOT NULL,
  forma_pagamento       text NOT NULL,
  comprovante_key       text NULL,
  status                text NOT NULL DEFAULT 'INICIADA',
  erro_mensagem         text NULL,
  gateway_cancelado_em  timestamptz NULL,
  concluida_em          timestamptz NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT baixas_manuais_valor_chk CHECK (valor_pago > 0),
  CONSTRAINT baixas_manuais_forma_chk CHECK (
    forma_pagamento IN ('PIX','BOLETO','TRANSFERENCIA','DINHEIRO','CARTAO')
  ),
  CONSTRAINT baixas_manuais_status_chk CHECK (
    status IN ('INICIADA','GATEWAY_CANCELADO','CONCLUIDA','FALHA')
  )
);
CREATE INDEX IF NOT EXISTS idx_baixas_manuais_status
  ON public.baixas_manuais (status, created_at);

COMMIT;
