-- =====================================================================
-- MIGRATION 008 — INTEGRIDADE FINANCEIRA, AUDITORIA E SESSÕES
-- =====================================================================

BEGIN;

-- Revogação de sessões após troca de senha.
ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS auth_version integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS password_changed_at timestamptz NULL;

-- O beneficiário financeiro é congelado no contrato. Trocas posteriores no
-- cadastro do imóvel não podem redirecionar parcelas já emitidas.
ALTER TABLE public.contratos
  ADD COLUMN IF NOT EXISTS proprietario_id_snapshot bigint NULL
    REFERENCES public.usuarios(id) ON DELETE RESTRICT;

UPDATE public.contratos c
SET proprietario_id_snapshot = i.proprietario_id
FROM public.imoveis i
WHERE i.id = c.imovel_id
  AND c.proprietario_id_snapshot IS NULL;

-- O UPDATE acima agenda os triggers diferidos de inquilino principal.
-- Executa-os antes dos ALTER TABLE seguintes.
SET CONSTRAINTS ALL IMMEDIATE;
SET CONSTRAINTS ALL DEFERRED;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.contratos
    WHERE proprietario_id_snapshot IS NULL
  ) THEN
    RAISE EXCEPTION
      'Existem contratos sem proprietário; corrija-os antes de aplicar a migration 008.';
  END IF;
END;
$$;

ALTER TABLE public.contratos
  ALTER COLUMN proprietario_id_snapshot SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_contratos_proprietario_snapshot
  ON public.contratos (proprietario_id_snapshot);

-- INADIMPLENTE continua ocupando o imóvel e continua no horizonte de cobrança.
ALTER TABLE public.contratos
  DROP CONSTRAINT IF EXISTS contratos_sem_sobreposicao;
ALTER TABLE public.contratos
  ADD CONSTRAINT contratos_sem_sobreposicao
  EXCLUDE USING gist (
    imovel_id WITH =,
    daterange(data_inicio, data_fim, '[]') WITH &&
  ) WHERE (status IN ('ATIVO', 'INADIMPLENTE'));

-- Uma caução pode possuir várias tentativas históricas, mas somente uma ativa.
ALTER TABLE public.caucao_cobrancas
  DROP CONSTRAINT IF EXISTS caucao_cobrancas_garantia_id_key;
ALTER TABLE public.caucao_cobrancas
  ADD COLUMN IF NOT EXISTS tentativa integer;

WITH numbered AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY garantia_id ORDER BY created_at, id
         )::integer AS tentativa
  FROM public.caucao_cobrancas
)
UPDATE public.caucao_cobrancas cc
SET tentativa = numbered.tentativa
FROM numbered
WHERE numbered.id = cc.id
  AND cc.tentativa IS NULL;

ALTER TABLE public.caucao_cobrancas
  ALTER COLUMN tentativa SET DEFAULT 1,
  ALTER COLUMN tentativa SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_caucao_tentativa
  ON public.caucao_cobrancas (garantia_id, tentativa);
CREATE UNIQUE INDEX IF NOT EXISTS uq_caucao_cobranca_ativa
  ON public.caucao_cobrancas (garantia_id) WHERE ativa;

-- Histórico imutável das revisões documentais.
CREATE TABLE IF NOT EXISTS public.cliente_documento_revisoes (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento_id    bigint NOT NULL
    REFERENCES public.cliente_documentos(id) ON DELETE CASCADE,
  status_anterior text NOT NULL,
  status_novo     text NOT NULL,
  observacao      text NULL,
  analisado_por   bigint NOT NULL
    REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cliente_documento_revisoes_status_chk CHECK (
    status_anterior IN ('PENDENTE','EM_ANALISE','APROVADO','REPROVADO')
    AND status_novo IN ('EM_ANALISE','APROVADO','REPROVADO')
  )
);
CREATE INDEX IF NOT EXISTS idx_documento_revisoes_documento
  ON public.cliente_documento_revisoes (documento_id, created_at DESC);

-- Auditoria das mudanças manuais de garantia/caução.
CREATE TABLE IF NOT EXISTS public.garantia_auditoria (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garantia_id  bigint NOT NULL
    REFERENCES public.garantias(id) ON DELETE RESTRICT,
  acao          text NOT NULL,
  estado_anterior jsonb NULL,
  estado_novo     jsonb NULL,
  realizado_por bigint NOT NULL
    REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_garantia_auditoria
  ON public.garantia_auditoria (garantia_id, created_at DESC);

-- O ator e a chave idempotente passam a fazer parte do repasse.
ALTER TABLE public.repasses
  ADD COLUMN IF NOT EXISTS solicitado_por bigint NULL
    REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS idempotency_key text NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_repasse_idempotency_key
  ON public.repasses (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Exclusões não podem apagar proprietário nem anonimizar quem realizou atos
-- financeiros/auditorias.
ALTER TABLE public.imoveis
  DROP CONSTRAINT IF EXISTS imoveis_proprietario_id_fkey;
ALTER TABLE public.imoveis
  ADD CONSTRAINT imoveis_proprietario_id_fkey
  FOREIGN KEY (proprietario_id) REFERENCES public.usuarios(id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.pagamentos
  DROP CONSTRAINT IF EXISTS pagamentos_registrado_por_fkey;
ALTER TABLE public.pagamentos
  ADD CONSTRAINT pagamentos_registrado_por_fkey
  FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
  ON DELETE RESTRICT;

ALTER TABLE public.baixas_manuais
  DROP CONSTRAINT IF EXISTS baixas_manuais_solicitado_por_fkey;
ALTER TABLE public.baixas_manuais
  ADD CONSTRAINT baixas_manuais_solicitado_por_fkey
  FOREIGN KEY (solicitado_por) REFERENCES public.usuarios(id)
  ON DELETE RESTRICT;

ALTER TABLE public.garantia_caucao
  DROP CONSTRAINT IF EXISTS garantia_caucao_analisado_por_fkey;
ALTER TABLE public.garantia_caucao
  ADD CONSTRAINT garantia_caucao_analisado_por_fkey
  FOREIGN KEY (analisado_por) REFERENCES public.usuarios(id)
  ON DELETE RESTRICT;

COMMIT;
