import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'crypto';
import { readFile } from 'fs/promises';
import pg from 'pg';

function monthDate(isoDate, monthOffset, day) {
  const source = new Date(`${isoDate}T00:00:00.000Z`);
  const result = new Date(
    Date.UTC(
      source.getUTCFullYear(),
      source.getUTCMonth() + monthOffset,
      day
    )
  );
  return result.toISOString().slice(0, 10);
}

test('fluxo PostgreSQL: contrato -> 12 boletos -> cliente -> webhook', async (t) => {
  if (!process.env.DATABASE_URL) {
    t.skip('DATABASE_URL não configurada.');
    return;
  }

  const schema = `billing_it_${randomUUID().replaceAll('-', '')}`;
  const adminPool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
    connectionTimeoutMillis: 10000,
  });
  const adminClient = await adminPool.connect();
  let appPool;

  try {
    await adminClient.query(`CREATE SCHEMA "${schema}"`);
    await adminClient.query(`SET search_path TO "${schema}"`);
    await adminClient.query(`
      CREATE TABLE usuarios (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome_completo text NOT NULL,
        documento text NOT NULL UNIQUE,
        email text,
        telefone text,
        perfil text,
        ativo boolean NOT NULL DEFAULT true
      );
      CREATE TABLE enderecos (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        logradouro text, numero text, bairro text, cidade text, estado text
      );
      CREATE TABLE imoveis (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        proprietario_id bigint REFERENCES usuarios(id),
        endereco_id bigint REFERENCES enderecos(id),
        tipo_imovel text,
        status text NOT NULL,
        valor_condominio numeric(12,2) NOT NULL DEFAULT 0,
        valor_iptu numeric(12,2) NOT NULL DEFAULT 0
      );
      CREATE TABLE contratos (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        imovel_id bigint NOT NULL REFERENCES imoveis(id),
        proprietario_id_snapshot bigint NOT NULL REFERENCES usuarios(id),
        corretor_id bigint,
        data_inicio date NOT NULL,
        data_fim date NOT NULL,
        valor_aluguel numeric(12,2) NOT NULL,
        dia_vencimento int NOT NULL,
        indice_reajuste text NOT NULL DEFAULT 'IGPM',
        periodicidade_reajuste_meses int NOT NULL DEFAULT 12,
        percentual_multa_atraso numeric(5,2) NOT NULL DEFAULT 2,
        percentual_juros_mora_mensal numeric(5,2) NOT NULL DEFAULT 1,
        dias_tolerancia int NOT NULL DEFAULT 0,
        taxa_administracao_percentual numeric(5,2) NOT NULL DEFAULT 0,
        comissao_tipo text NOT NULL DEFAULT 'PERCENTUAL',
        comissao_valor_fixo numeric(12,2),
        data_devolucao_imovel date,
        status text NOT NULL DEFAULT 'ATIVO',
        observacoes text,
        migrado boolean NOT NULL DEFAULT false,
        cobrancas_iniciais_iniciadas_em timestamptz NOT NULL DEFAULT now(),
        cobrancas_iniciais_a_partir_de date NOT NULL DEFAULT CURRENT_DATE,
        cobrancas_iniciais_concluidas_em timestamptz
      );
      CREATE TABLE contrato_inquilinos (
        contrato_id bigint NOT NULL REFERENCES contratos(id),
        usuario_id bigint NOT NULL REFERENCES usuarios(id),
        principal boolean NOT NULL DEFAULT false,
        PRIMARY KEY (contrato_id, usuario_id)
      );
      CREATE UNIQUE INDEX uq_inquilino_principal
        ON contrato_inquilinos (contrato_id) WHERE principal;
      CREATE TABLE gateway_customers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        usuario_id bigint NOT NULL REFERENCES usuarios(id),
        gateway text NOT NULL,
        external_customer_id text NOT NULL,
        UNIQUE (usuario_id, gateway),
        UNIQUE (gateway, external_customer_id)
      );
      CREATE TABLE parcelas (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        contrato_id bigint NOT NULL REFERENCES contratos(id) ON DELETE RESTRICT,
        competencia date NOT NULL,
        data_vencimento date NOT NULL,
        valor_base numeric(12,2) NOT NULL,
        status text NOT NULL,
        forma_pagamento text,
        external_reference text,
        tentativa int NOT NULL DEFAULT 1,
        UNIQUE (contrato_id, competencia),
        UNIQUE (external_reference)
      );
      CREATE TABLE parcela_lancamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcela_id bigint NOT NULL REFERENCES parcelas(id),
        tipo text NOT NULL,
        descricao text,
        valor numeric(12,2) NOT NULL,
        beneficiario text NOT NULL
      );
      CREATE TABLE gateway_cobrancas (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcela_id bigint NOT NULL REFERENCES parcelas(id),
        gateway text NOT NULL,
        external_payment_id text NOT NULL,
        linha_digitavel text,
        codigo_barras text,
        url_boleto text,
        url_fatura text,
        qr_code_pix text,
        copia_cola_pix text,
        valor numeric(12,2) NOT NULL,
        data_vencimento date NOT NULL,
        status_gateway text,
        raw_json jsonb,
        ativa boolean NOT NULL DEFAULT true,
        created_at timestamptz NOT NULL DEFAULT now(),
        UNIQUE (gateway, external_payment_id)
      );
      CREATE UNIQUE INDEX uq_gateway_cobranca_ativa
        ON gateway_cobrancas (parcela_id) WHERE ativa;
      CREATE TABLE pagamentos (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcela_id bigint NOT NULL REFERENCES parcelas(id),
        valor_pago numeric(12,2) NOT NULL,
        data_pagamento date NOT NULL,
        forma_pagamento text NOT NULL,
        comprovante_url text,
        comprovante_key text,
        registrado_por bigint,
        origem text NOT NULL DEFAULT 'GATEWAY',
        gateway_event_id text,
        estornado_em timestamptz
      );
      CREATE UNIQUE INDEX uq_pagamento_gateway_event
        ON pagamentos (gateway_event_id) WHERE gateway_event_id IS NOT NULL;
      CREATE TABLE baixas_manuais (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcela_id bigint NOT NULL UNIQUE REFERENCES parcelas(id),
        gateway_cobranca_id bigint NOT NULL REFERENCES gateway_cobrancas(id),
        solicitado_por bigint REFERENCES usuarios(id),
        valor_pago numeric(12,2) NOT NULL,
        data_pagamento date NOT NULL,
        forma_pagamento text NOT NULL,
        comprovante_key text,
        status text NOT NULL DEFAULT 'INICIADA',
        erro_mensagem text,
        gateway_cancelado_em timestamptz,
        concluida_em timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE TABLE webhook_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gateway text NOT NULL,
        external_event_id text NOT NULL,
        event_type text NOT NULL,
        payload_json jsonb NOT NULL,
        status text NOT NULL DEFAULT 'RECEBIDO',
        tentativas int NOT NULL DEFAULT 0,
        proxima_tentativa_em timestamptz NOT NULL DEFAULT now(),
        erro_mensagem text,
        recebido_em timestamptz NOT NULL DEFAULT now(),
        processado_em timestamptz,
        descartado_em timestamptz,
        UNIQUE (gateway, external_event_id)
      );
    `);

    const tenantMigrationUrl = new URL(
      '../docs/migrations/006_inquilino_principal.sql',
      import.meta.url
    );
    const tenantMigration = (await readFile(tenantMigrationUrl, 'utf8'))
      .replace(/^\s*BEGIN;\s*$/im, '')
      .replace(/^\s*COMMIT;\s*$/im, '')
      .replaceAll('public.', `"${schema}".`);
    await adminClient.query(tenantMigration);

    const scopedUrl = new URL(process.env.DATABASE_URL);
    scopedUrl.searchParams.set('options', `-c search_path=${schema}`);
    process.env.DATABASE_URL = scopedUrl.toString();
    process.env.PAYMENT_GATEWAY_PROVIDER = 'FAKE';
    process.env.SUPABASE_URL ||= 'http://localhost:54321';
    process.env.SUPABASE_SECRET_KEY ||= 'integration-test';

    const { dataAtualIso } = await import('../src/utils/businessDays.js');
    const { default: ContractsService } = await import(
      '../src/services/contracts.service.js'
    );
    const { default: PaymentsService } = await import(
      '../src/services/payments.service.js'
    );
    const { default: BillingService } = await import(
      '../src/services/billing.service.js'
    );
    const { default: WebhooksService } = await import(
      '../src/services/webhooks.service.js'
    );
    ({ pool: appPool } = await import('../src/config/database.js'));

    const today = dataAtualIso();
    const dataInicio = monthDate(today, 0, 1);
    const dataFim = monthDate(today, 18, 28);
    const diaVencimento = 28;
    const owner = await appPool.query(
      `INSERT INTO usuarios (nome_completo, documento, email, perfil)
       VALUES ('Proprietário', '12345678901', 'owner@example.com', 'CLIENTE')
       RETURNING id`
    );
    const tenant = await appPool.query(
      `INSERT INTO usuarios (nome_completo, documento, email, telefone, perfil)
       VALUES ('Inquilino', '12345678902', 'tenant@example.com', '48999999999', 'CLIENTE')
      RETURNING id`
    );
    const coTenant = await appPool.query(
      `INSERT INTO usuarios (nome_completo, documento, email, perfil)
       VALUES ('Co-inquilino', '12345678904', 'cotenant@example.com', 'CLIENTE')
       RETURNING id`
    );
    const unrelatedTenant = await appPool.query(
      `INSERT INTO usuarios (nome_completo, documento, email, perfil)
       VALUES ('Outro Inquilino', '12345678903', 'other@example.com', 'CLIENTE')
       RETURNING id`
    );
    const address = await appPool.query(
      `INSERT INTO enderecos (logradouro, numero, bairro, cidade, estado)
       VALUES ('Rua Teste', '10', 'Centro', 'Tijucas', 'SC') RETURNING id`
    );
    const property = await appPool.query(
      `INSERT INTO imoveis (
         proprietario_id, endereco_id, tipo_imovel, status,
         valor_condominio, valor_iptu
       ) VALUES ($1, $2, 'APARTAMENTO', 'DISPONIVEL', 100, 50)
       RETURNING id`,
      [owner.rows[0].id, address.rows[0].id]
    );

    const result = await ContractsService.registerContract({
      imovelId: property.rows[0].id,
      dataInicio,
      dataFim,
      valorAluguel: 1000,
      diaVencimento,
      taxaAdministracaoPercentual: 10,
      inquilinos: [
        { usuarioId: tenant.rows[0].id, principal: true },
        { usuarioId: coTenant.rows[0].id, principal: false },
      ],
    });

    assert.equal(result.cobrancas.completo, true);
    assert.equal(result.cobrancas.geradas, 12);
    const persisted = await appPool.query(
      `SELECT
         (SELECT count(*)::int FROM parcelas WHERE contrato_id = $1) parcelas,
         (SELECT count(*)::int FROM gateway_cobrancas gc
            JOIN parcelas p ON p.id = gc.parcela_id
           WHERE p.contrato_id = $1) cobrancas,
         (SELECT count(*)::int FROM gateway_customers
           WHERE usuario_id = $2 AND gateway = 'FAKE') customers,
         (SELECT count(*)::int FROM gateway_customers
           WHERE usuario_id = $3 AND gateway = 'FAKE') co_tenant_customers,
         (SELECT count(*)::int FROM contrato_inquilinos
           WHERE contrato_id = $1) linked_tenants,
         (SELECT cobrancas_iniciais_concluidas_em IS NOT NULL
            FROM contratos WHERE id = $1) lote_concluido`,
      [result.contrato.id, tenant.rows[0].id, coTenant.rows[0].id]
    );
    assert.deepEqual(persisted.rows[0], {
      parcelas: 12,
      cobrancas: 12,
      customers: 1,
      co_tenant_customers: 0,
      linked_tenants: 2,
      lote_concluido: true,
    });

    const clientPayments = await PaymentsService.getMyPayments(
      tenant.rows[0].id
    );
    assert.equal(clientPayments.length, 12);
    assert.ok(clientPayments[0].cobranca.urlBoleto);
    const firstFuture = clientPayments.find(
      (payment) => payment.dataVencimentoEfetiva >= today
    );
    assert.equal(clientPayments[0].id, firstFuture.id);
    const ownBoleto = await PaymentsService.getMyBoleto(
      clientPayments[0].id,
      tenant.rows[0].id
    );
    assert.ok(ownBoleto.urlBoleto);
    assert.equal(String(ownBoleto.parcelaId), String(clientPayments[0].id));

    const coTenantPayments = await PaymentsService.getMyPayments(
      coTenant.rows[0].id
    );
    assert.equal(coTenantPayments.length, 12);
    const coTenantBoleto = await PaymentsService.getMyBoleto(
      coTenantPayments[0].id,
      coTenant.rows[0].id
    );
    assert.equal(coTenantBoleto.urlBoleto, ownBoleto.urlBoleto);

    const manualTarget = clientPayments[1];
    const manualPayment = await BillingService.registrarBaixaManual(
      manualTarget.id,
      {
        dataPagamento: today,
        formaPagamento: 'DINHEIRO',
        valorPago: manualTarget.valorTotal,
      },
      tenant.rows[0].id
    );
    assert.equal(manualPayment.status, 'CONCLUIDA');
    const manualPersisted = await appPool.query(
      `SELECT p.status, gc.ativa, pay.origem, pay.registrado_por,
              bm.status AS baixa_status, bm.gateway_cancelado_em IS NOT NULL AS cancelado
       FROM parcelas p
       JOIN gateway_cobrancas gc ON gc.parcela_id = p.id
       JOIN pagamentos pay ON pay.parcela_id = p.id
       JOIN baixas_manuais bm ON bm.parcela_id = p.id
       WHERE p.id = $1`,
      [manualTarget.id]
    );
    assert.deepEqual(manualPersisted.rows[0], {
      status: 'PAGA',
      ativa: false,
      origem: 'PRESENCIAL',
      registrado_por: tenant.rows[0].id,
      baixa_status: 'CONCLUIDA',
      cancelado: true,
    });

    const migratedProperty = await appPool.query(
      `INSERT INTO imoveis (
         proprietario_id, endereco_id, tipo_imovel, status,
         valor_condominio, valor_iptu
       ) VALUES ($1, $2, 'CASA', 'ALUGADO', 0, 0) RETURNING id`,
      [owner.rows[0].id, address.rows[0].id]
    );
    const migrationClient = await appPool.connect();
    let migratedContractId;
    try {
      await migrationClient.query('BEGIN');
      const migratedContract = await migrationClient.query(
        `INSERT INTO contratos (
           imovel_id, proprietario_id_snapshot, data_inicio, data_fim, valor_aluguel, dia_vencimento,
           migrado, cobrancas_iniciais_a_partir_de
         ) VALUES ($1, $2, $3, $4, 900, 10, true, CURRENT_DATE)
         RETURNING id`,
        [
          migratedProperty.rows[0].id,
          owner.rows[0].id,
          monthDate(today, -12, 1),
          monthDate(today, 12, 28),
        ]
      );
      migratedContractId = migratedContract.rows[0].id;
      await migrationClient.query(
        `INSERT INTO contrato_inquilinos (contrato_id, usuario_id, principal)
         VALUES ($1, $2, true)`,
        [migratedContractId, tenant.rows[0].id]
      );
      await migrationClient.query('COMMIT');
    } finally {
      await migrationClient.query('ROLLBACK').catch(() => undefined);
      migrationClient.release();
    }
    const historicalCompetence = monthDate(today, -2, 1);
    await ContractsService.registerHistoricalPayments(
      migratedContractId,
      [{
        competencia: historicalCompetence,
        dataVencimento: monthDate(today, -2, 10),
        dataPagamento: monthDate(today, -2, 9),
        valorPago: 900,
        formaPagamento: 'TRANSFERENCIA',
      }],
      tenant.rows[0].id
    );
    const historicalPersisted = await appPool.query(
      `SELECT p.status, pay.origem,
              NOT EXISTS (SELECT 1 FROM gateway_cobrancas gc WHERE gc.parcela_id = p.id) AS sem_gateway
       FROM parcelas p JOIN pagamentos pay ON pay.parcela_id = p.id
       WHERE p.contrato_id = $1 AND p.competencia = $2`,
      [migratedContractId, historicalCompetence]
    );
    assert.deepEqual(historicalPersisted.rows[0], {
      status: 'PAGA', origem: 'MIGRACAO', sem_gateway: true,
    });

    await assert.rejects(
      PaymentsService.getMyBoleto(
        clientPayments[0].id,
        unrelatedTenant.rows[0].id
      ),
      (error) => error.statusCode === 404
    );

    const contractUpdateData = {
      dataInicio,
      dataFim,
      valorAluguel: 1000,
      diaVencimento,
      indiceReajuste: 'IGPM',
      periodicidadeReajusteMeses: 12,
      percentualMultaAtraso: 2,
      percentualJurosMoraMensal: 1,
      diasTolerancia: 0,
      taxaAdministracaoPercentual: 10,
    };

    // Co-inquilinos podem ser atualizados e passam a acessar todo o histórico.
    // O titular permanece imutável depois que os boletos foram emitidos.
    await ContractsService.updateContract(result.contrato.id, {
      ...contractUpdateData,
      inquilinos: [
        { usuarioId: tenant.rows[0].id, principal: true },
        { usuarioId: unrelatedTenant.rows[0].id, principal: false },
      ],
    });
    const newlyLinkedPayments = await PaymentsService.getMyPayments(
      unrelatedTenant.rows[0].id
    );
    assert.equal(newlyLinkedPayments.length, 12);
    await assert.rejects(
      PaymentsService.getMyBoleto(
        clientPayments[0].id,
        coTenant.rows[0].id
      ),
      (error) => error.statusCode === 404
    );
    await assert.rejects(
      ContractsService.updateContract(result.contrato.id, {
        ...contractUpdateData,
        inquilinos: [
          { usuarioId: tenant.rows[0].id, principal: false },
          { usuarioId: unrelatedTenant.rows[0].id, principal: true },
        ],
      }),
      (error) =>
        error.statusCode === 409 &&
        error.message.includes('inquilino principal')
    );

    const target = clientPayments[0];
    const externalPaymentId = `pay_integration_${randomUUID()}`;
    const webhook = {
      id: `evt_received_${randomUUID()}`,
      event: 'PAYMENT_RECEIVED',
      payment: {
        id: externalPaymentId,
        externalReference: `contrato-${result.contrato.id}-${target.competencia}`,
        value: target.valorTotal,
        paymentDate: today,
        billingType: 'BOLETO',
        status: 'RECEIVED',
      },
    };
    const primeiraTentativa = await WebhooksService.processarAsaas(webhook);
    assert.equal(primeiraTentativa.erro, true);
    assert.equal(primeiraTentativa.statusInbox, 'ERRO');
    const prematureEvents = await appPool.query(
      `SELECT count(*)::int AS count, max(status) AS status,
              max(tentativas)::int AS tentativas
         FROM webhook_events
       WHERE external_event_id = $1`,
      [webhook.id]
    );
    assert.deepEqual(prematureEvents.rows[0], {
      count: 1,
      status: 'ERRO',
      tentativas: 1,
    });

    await appPool.query(
      `UPDATE gateway_cobrancas
       SET gateway = 'ASAAS', external_payment_id = $1
      WHERE parcela_id = $2`,
      [externalPaymentId, target.id]
    );
    await appPool.query(
      `UPDATE webhook_events
       SET proxima_tentativa_em = now()
       WHERE external_event_id = $1`,
      [webhook.id]
    );
    const retry = await WebhooksService.processarPendentes({ limite: 10 });
    const received = retry.resultados.find(
      (item) => String(item.eventoId) === String(primeiraTentativa.eventoId)
    );
    const duplicate = await WebhooksService.processarAsaas(webhook);
    assert.equal(received.status, 'RECEBIDA');
    assert.equal(received.statusInbox, 'PROCESSADO');
    assert.equal(duplicate.ignorado, true);

    const paid = await appPool.query(
      `SELECT p.status,
              (SELECT count(*)::int FROM pagamentos pay
                WHERE pay.parcela_id = p.id) pagamentos,
              (SELECT max(gateway_event_id) FROM pagamentos pay
                WHERE pay.parcela_id = p.id) gateway_event_id
       FROM parcelas p WHERE p.id = $1`,
      [target.id]
    );
    assert.deepEqual(paid.rows[0], {
      status: 'RECEBIDA',
      pagamentos: 1,
      gateway_event_id: webhook.id,
    });

    const paidCharge = await appPool.query(
      `SELECT ativa FROM gateway_cobrancas WHERE parcela_id = $1`,
      [target.id]
    );
    assert.equal(paidCharge.rows[0].ativa, false);

    // Mesmo não sendo mais pagável, o boleto continua consultável pelo dono
    // para histórico/suporte.
    const historicalBoleto = await PaymentsService.getMyBoleto(
      target.id,
      tenant.rows[0].id
    );
    assert.equal(historicalBoleto.externalPaymentId, externalPaymentId);
    assert.equal(historicalBoleto.ativa, false);

    const lateConfirmed = await WebhooksService.processarAsaas({
      id: `evt_late_confirmed_${randomUUID()}`,
      event: 'PAYMENT_CONFIRMED',
      payment: {
        ...webhook.payment,
        status: 'CONFIRMED',
      },
    });
    assert.equal(lateConfirmed.status, 'RECEBIDA');
    const afterLateConfirmed = await appPool.query(
      `SELECT ativa, status_gateway
       FROM gateway_cobrancas WHERE parcela_id = $1`,
      [target.id]
    );
    assert.deepEqual(afterLateConfirmed.rows[0], {
      ativa: false,
      status_gateway: 'RECEIVED',
    });

    const partialRefund = await WebhooksService.processarAsaas({
      id: `evt_partial_refund_${randomUUID()}`,
      event: 'PAYMENT_PARTIALLY_REFUNDED',
      payment: {
        ...webhook.payment,
        status: 'PARTIALLY_REFUNDED',
        refunds: [{ status: 'DONE', value: 10 }],
      },
    });
    assert.equal(partialRefund.statusInbox, 'IGNORADO');
    assert.equal(
      partialRefund.motivo,
      'estorno_parcial_requer_conciliacao_de_valores'
    );
    const afterPartialRefund = await appPool.query(
      `SELECT p.status, gc.ativa, gc.status_gateway
       FROM parcelas p
       JOIN gateway_cobrancas gc ON gc.parcela_id = p.id
       WHERE p.id = $1`,
      [target.id]
    );
    assert.deepEqual(afterPartialRefund.rows[0], {
      status: 'RECEBIDA',
      ativa: false,
      status_gateway: 'PAYMENT_PARTIALLY_REFUNDED',
    });

    const deletedTarget = clientPayments.find(
      (item) => item.id !== target.id && item.id !== manualTarget.id
    );
    const deletedExternalPaymentId = `pay_deleted_${randomUUID()}`;
    await appPool.query(
      `UPDATE gateway_cobrancas
       SET gateway = 'ASAAS', external_payment_id = $1
       WHERE parcela_id = $2`,
      [deletedExternalPaymentId, deletedTarget.id]
    );
    const deletedResult = await WebhooksService.processarAsaas({
      id: `evt_deleted_${randomUUID()}`,
      event: 'PAYMENT_DELETED',
      payment: {
        id: deletedExternalPaymentId,
        externalReference:
          `contrato-${result.contrato.id}-${deletedTarget.competencia}`,
        status: 'PENDING',
      },
    });
    assert.equal(deletedResult.status, 'CANCELADA');
    const deletedCharge = await appPool.query(
      `SELECT p.status, gc.ativa, gc.status_gateway
       FROM parcelas p
       JOIN gateway_cobrancas gc ON gc.parcela_id = p.id
       WHERE p.id = $1`,
      [deletedTarget.id]
    );
    assert.deepEqual(deletedCharge.rows[0], {
      status: 'CANCELADA',
      ativa: false,
      status_gateway: 'PAYMENT_DELETED',
    });
    const deletedHistory = await PaymentsService.getMyBoleto(
      deletedTarget.id,
      tenant.rows[0].id
    );
    assert.equal(deletedHistory.ativa, false);

    // Simula o encerramento operacional das demais competências. A cobrança
    // recebida acima não pode continuar bloqueando o fim do contrato.
    await appPool.query(
      `UPDATE gateway_cobrancas gc
       SET ativa = false
       FROM parcelas p
       WHERE p.id = gc.parcela_id
         AND p.contrato_id = $1
         AND p.id <> $2`,
      [result.contrato.id, target.id]
    );
    await appPool.query(
      `UPDATE parcelas
       SET status = 'CANCELADA'
       WHERE contrato_id = $1 AND id <> $2`,
      [result.contrato.id, target.id]
    );
    await ContractsService.updateContract(result.contrato.id, {
      dataInicio,
      dataFim,
      valorAluguel: 1000,
      diaVencimento,
      indiceReajuste: 'IGPM',
      periodicidadeReajusteMeses: 12,
      percentualMultaAtraso: 2,
      percentualJurosMoraMensal: 1,
      diasTolerancia: 0,
      taxaAdministracaoPercentual: 10,
      dataDevolucaoImovel: today,
      status: 'ENCERRADO',
    });
    const endedContract = await appPool.query(
      `SELECT status FROM contratos WHERE id = $1`,
      [result.contrato.id]
    );
    assert.equal(endedContract.rows[0].status, 'ENCERRADO');

    const previousMaxAttempts = process.env.WEBHOOK_MAX_ATTEMPTS;
    process.env.WEBHOOK_MAX_ATTEMPTS = '2';
    const missingValueEventId = `evt_missing_value_${randomUUID()}`;

    try {
      const semValor = await WebhooksService.processarAsaas({
        id: missingValueEventId,
        event: 'PAYMENT_RECEIVED',
        payment: {
          id: externalPaymentId,
          externalReference: webhook.payment.externalReference,
          status: 'RECEIVED',
        },
      });
      assert.equal(semValor.erro, true);
      assert.equal(semValor.statusInbox, 'ERRO');

      await appPool.query(
        `UPDATE webhook_events SET proxima_tentativa_em = now()
         WHERE external_event_id = $1`,
        [missingValueEventId]
      );
      const deadLetterRetry = await WebhooksService.processarPendentes({
        limite: 1,
      });
      assert.equal(deadLetterRetry.descartados, 1);

      const deadLetter = await appPool.query(
        `SELECT status, tentativas, descartado_em IS NOT NULL AS descartado
         FROM webhook_events WHERE external_event_id = $1`,
        [missingValueEventId]
      );
      assert.deepEqual(deadLetter.rows[0], {
        status: 'DESCARTADO',
        tentativas: 2,
        descartado: true,
      });
    } finally {
      if (previousMaxAttempts === undefined) {
        delete process.env.WEBHOOK_MAX_ATTEMPTS;
      } else {
        process.env.WEBHOOK_MAX_ATTEMPTS = previousMaxAttempts;
      }
    }

    const desconhecido = await WebhooksService.processarAsaas({
      id: `evt_unknown_${randomUUID()}`,
      event: 'CUSTOMER_UPDATED',
    });
    assert.equal(desconhecido.statusInbox, 'IGNORADO');

    await WebhooksService.processarAsaas({
      id: `evt_refunded_${randomUUID()}`,
      event: 'PAYMENT_REFUNDED',
      payment: {
        ...webhook.payment,
        status: 'REFUNDED',
      },
    });
    const refunded = await PaymentsService.getMyPayments(tenant.rows[0].id);
    const refundedTarget = refunded.find((payment) => payment.id === target.id);
    assert.equal(refundedTarget.statusEfetivo, 'ESTORNADA');
    assert.equal(refundedTarget.valorPago, 0);
  } finally {
    await appPool?.end().catch(() => undefined);
    await adminClient.query(`RESET search_path`).catch(() => undefined);
    await adminClient
      .query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`)
      .catch(() => undefined);
    adminClient.release();
    await adminPool.end();
  }
});
