-- =====================================================================
-- SISTEMA DE GERENCIAMENTO DE ALUGUÉIS — MODELO REFATORADO (PostgreSQL)
-- Variante: PESSOA + USUÁRIO em uma única tabela (`usuarios`)
-- =====================================================================
-- Convenções:
--   - PK bigint identity (compatível com o schema atual).
--   - Dinheiro em numeric(12,2). Nunca float.
--   - Enums via text + CHECK. Troque por CREATE TYPE ... AS ENUM se
--     quiser tipagem forte no banco.
--   - `usuarios` guarda cadastro + autenticação. senha_hash/perfil são
--     NULL para quem não loga (proprietário, fiador). A identidade real
--     da linha é `documento`. Papéis de negócio (proprietário/inquilino/
--     fiador) são RELACIONAMENTOS, nunca colunas booleanas.
-- =====================================================================

-- =====================================================================
-- RESET — apaga TODAS as tabelas deste modelo (e TODOS os dados!).
-- Destrutivo e irreversível. Roda antes de recriar tudo do zero.
-- CASCADE derruba FKs, índices e triggers dependentes junto.
-- =====================================================================
DROP TABLE IF EXISTS
  public.pagamentos,
  public.boletos,
  public.parcela_lancamentos,
  public.parcelas,
  public.reajustes,
  public.garantia_seguro_fianca,
  public.garantia_fiadores,
  public.garantia_caucao,
  public.garantias,
  public.contrato_fiadores,   -- substituída por garantia_fiadores (migration 001)
  public.contrato_inquilinos,
  public.contratos,
  public.imoveis,
  public.contas_bancarias,
  public.codigo_verificacao,
  public.usuarios,
  public.pessoas,          -- caso exista de uma versão anterior do modelo
  public.enderecos
CASCADE;

DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS public.valida_caucao_dinheiro() CASCADE;

-- =====================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- BLOCO 1 — ENDEREÇOS, USUÁRIOS/PESSOAS E ACESSO
-- =====================================================================

CREATE TABLE public.enderecos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pais         text    NOT NULL DEFAULT 'Brasil',
  cep          text    NOT NULL,
  estado       char(2) NOT NULL,
  cidade       text    NOT NULL,
  bairro       text    NOT NULL,
  logradouro   text    NOT NULL,
  numero       text    NULL,
  complemento  text    NULL,
  latitude     numeric(10,7) NULL,
  longitude    numeric(10,7) NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_enderecos_updated BEFORE UPDATE ON public.enderecos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- USUARIOS = cadastro (party) + autenticação, numa tabela só ----------
CREATE TABLE public.usuarios (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Cadastro (todo proprietário, inquilino, fiador e corretor é uma linha aqui)
  nome_completo     text    NOT NULL,          -- razão social se PJ
  documento         text    NOT NULL,          -- CPF/CNPJ: só dígitos
  -- Derivado do documento: 14 dígitos = CNPJ = PJ; senão PF
  tipo_pessoa       text    GENERATED ALWAYS AS (
                      CASE WHEN length(documento) = 14 THEN 'PJ' ELSE 'PF' END
                    ) STORED,
  rg                text    NULL,              -- RG (PF); opcional
  email             text    NULL,              -- contato + login
  telefone          text    NULL,
  data_nascimento   date    NULL,
  endereco_id       bigint  NULL REFERENCES public.enderecos(id) ON DELETE SET NULL,
  -- Autenticação (NULL para quem não loga)
  senha_hash        text    NULL,
  perfil            text    NULL,              -- ADMIN/CORRETOR/CLIENTE
  email_verificado  boolean NOT NULL DEFAULT false,
  ultimo_login      timestamptz NULL,
  ativo             boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_documento_key UNIQUE (documento),
  CONSTRAINT usuarios_email_key     UNIQUE (email),
  CONSTRAINT usuarios_telefone_key  UNIQUE (telefone),
  CONSTRAINT usuarios_doc_chk    CHECK (documento ~ '^[0-9]+$' AND length(documento) IN (11,14)),
  CONSTRAINT usuarios_perfil_chk CHECK (perfil IS NULL OR perfil IN ('ADMIN','CORRETOR','CLIENTE')),
  CONSTRAINT usuarios_login_chk  CHECK (senha_hash IS NULL OR email IS NOT NULL)
);
CREATE TRIGGER trg_usuarios_updated BEFORE UPDATE ON public.usuarios
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CODIGO_VERIFICACAO (PK própria, tipo, uso, histórico) ---------------
CREATE TABLE public.codigo_verificacao (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id  bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  codigo      text   NOT NULL,
  tipo        text   NOT NULL DEFAULT 'VERIFICACAO_EMAIL',
  expires_at  timestamptz NULL,
  usado_em    timestamptz NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT codigo_tipo_chk CHECK (tipo IN ('VERIFICACAO_EMAIL','RESET_SENHA'))
);
CREATE INDEX idx_codigo_usuario ON public.codigo_verificacao (usuario_id, tipo);

-- CONTAS_BANCARIAS (do usuário/pessoa que recebe o aluguel) -----------
CREATE TABLE public.contas_bancarias (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id  bigint  NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  banco       text    NOT NULL,
  agencia     text    NOT NULL,
  conta       text    NOT NULL,
  tipo_conta  text    NOT NULL,
  chave_pix   text    NULL,
  principal   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_conta_principal_por_usuario
  ON public.contas_bancarias (usuario_id) WHERE principal;

-- =====================================================================
-- BLOCO 2 — IMÓVEIS
-- =====================================================================

CREATE TABLE public.imoveis (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endereco_id               bigint NOT NULL REFERENCES public.enderecos(id) ON DELETE RESTRICT,
  -- Único responsável (proprietário) pelo imóvel.
  proprietario_id           bigint NULL REFERENCES public.usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo_imovel               text   NOT NULL,
  valor_aluguel_referencia  numeric(12,2) NOT NULL,
  valor_condominio          numeric(12,2) NULL,
  valor_iptu                numeric(12,2) NULL,
  area_util                 numeric(10,2) NULL,
  quartos                   int NULL,
  banheiros                 int NULL,
  vagas_garagem             int NULL,
  matricula                 text NULL,
  inscricao_iptu            text NULL,
  observacoes               text NULL,
  status                    text NOT NULL DEFAULT 'DISPONIVEL',
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT imoveis_status_chk CHECK (status IN ('DISPONIVEL','ALUGADO','MANUTENCAO','INATIVO')),
  CONSTRAINT imoveis_tipo_chk   CHECK (tipo_imovel IN ('CASA','APARTAMENTO','COMERCIAL','TERRENO','GALPAO','OUTRO')),
  CONSTRAINT imoveis_valor_chk  CHECK (valor_aluguel_referencia >= 0)
);
CREATE TRIGGER trg_imoveis_updated BEFORE UPDATE ON public.imoveis
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_imoveis_proprietario ON public.imoveis (proprietario_id);

-- Obs.: o vínculo imóvel ↔ proprietário deixou de ser N:N.
-- Agora há um único responsável por imóvel em imoveis.proprietario_id.

-- =====================================================================
-- BLOCO 3 — CONTRATOS
-- =====================================================================

CREATE TABLE public.contratos (
  id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imovel_id                     bigint NOT NULL REFERENCES public.imoveis(id) ON DELETE RESTRICT,
  corretor_id                   bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  data_inicio                   date   NOT NULL,
  data_fim                      date   NOT NULL,
  valor_aluguel                 numeric(12,2) NOT NULL,
  dia_vencimento                int    NOT NULL,
  indice_reajuste               text   NOT NULL DEFAULT 'IGPM',
  periodicidade_reajuste_meses  int    NOT NULL DEFAULT 12,
  percentual_multa_atraso       numeric(5,2) NOT NULL DEFAULT 2,
  percentual_juros_mora_mensal  numeric(5,2) NOT NULL DEFAULT 1,
  dias_tolerancia               int    NOT NULL DEFAULT 0,
  taxa_administracao_percentual numeric(5,2) NOT NULL DEFAULT 0,
  -- Art. 39: a garantia se estende até a DEVOLUÇÃO EFETIVA do imóvel, que pode
  -- ocorrer depois de data_fim (locação prorrogada por prazo indeterminado).
  data_devolucao_imovel         date   NULL,
  status                        text   NOT NULL DEFAULT 'ATIVO',
  observacoes                   text   NULL,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contratos_status_chk    CHECK (status IN ('ATIVO','ENCERRADO','RESCINDIDO','INADIMPLENTE')),
  CONSTRAINT contratos_indice_chk    CHECK (indice_reajuste IN ('IGPM','IPCA','INPC','FIXO')),
  CONSTRAINT contratos_dia_venc_chk  CHECK (dia_vencimento BETWEEN 1 AND 28),
  CONSTRAINT contratos_valor_chk     CHECK (valor_aluguel >= 0),
  CONSTRAINT contratos_datas_chk     CHECK (data_fim > data_inicio),
  -- Lei 10.192/2001: reajuste com periodicidade mínima anual.
  CONSTRAINT contratos_reajuste_chk  CHECK (periodicidade_reajuste_meses >= 12),
  CONSTRAINT contratos_pct_chk       CHECK (
      percentual_multa_atraso       BETWEEN 0 AND 100 AND
      percentual_juros_mora_mensal  BETWEEN 0 AND 100 AND
      taxa_administracao_percentual BETWEEN 0 AND 100
  )
);

-- Obs.: a garantia NÃO fica mais em `contratos` (tipo_garantia/valor_caucao foram
-- removidos na migration 001). Ela vive no BLOCO 3.1, e a ausência de garantia
-- ATIVA significa locação sem garantia (art. 42 da Lei 8.245/91).
CREATE TRIGGER trg_contratos_updated BEFORE UPDATE ON public.contratos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Um imóvel não pode ter dois contratos ATIVOS com períodos sobrepostos
ALTER TABLE public.contratos
  ADD CONSTRAINT contratos_sem_sobreposicao
  EXCLUDE USING gist (
    imovel_id WITH =,
    daterange(data_inicio, data_fim, '[]') WITH &&
  ) WHERE (status = 'ATIVO');

CREATE INDEX idx_contratos_imovel   ON public.contratos (imovel_id);
CREATE INDEX idx_contratos_status   ON public.contratos (status);
CREATE INDEX idx_contratos_data_fim ON public.contratos (data_fim);

-- N:N contrato ↔ inquilinos -------------------------------------------
CREATE TABLE public.contrato_inquilinos (
  contrato_id bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  usuario_id  bigint NOT NULL REFERENCES public.usuarios(id)  ON DELETE RESTRICT,
  principal   boolean NOT NULL DEFAULT false,
  PRIMARY KEY (contrato_id, usuario_id)
);
CREATE INDEX idx_contrato_inq_usuario ON public.contrato_inquilinos (usuario_id);
CREATE UNIQUE INDEX uq_inquilino_principal
  ON public.contrato_inquilinos (contrato_id) WHERE principal;

-- =====================================================================
-- BLOCO 3.1 — GARANTIAS LOCATÍCIAS (Lei 8.245/91, arts. 37 a 42)
-- =====================================================================
-- Modelo supertipo + detalhe. A modalidade da garantia é um RELACIONAMENTO,
-- nunca uma coluna solta em `contratos`.
--
--   garantias
--     ├── garantia_caucao         (1:1)
--     ├── garantia_fiadores       (1:N)
--     └── garantia_seguro_fianca  (1:1)
--
-- Ausência de garantia ATIVA = locação sem garantia (art. 42: nesse caso o
-- locador pode exigir o aluguel até o 6º dia útil do mês vincendo).
-- =====================================================================

CREATE TABLE public.garantias (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id         bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  tipo                text   NOT NULL,                   -- CAUCAO | FIADOR | SEGURO_FIANCA
  status              text   NOT NULL DEFAULT 'ATIVA',   -- ATIVA | SUBSTITUIDA | ENCERRADA
  data_inicio         date   NOT NULL DEFAULT CURRENT_DATE,
  data_fim            date   NULL,                       -- preenchida ao substituir/encerrar
  motivo_substituicao text   NULL,                       -- art. 40
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT garantias_tipo_chk   CHECK (tipo IN ('CAUCAO','FIADOR','SEGURO_FIANCA')),
  CONSTRAINT garantias_status_chk CHECK (status IN ('ATIVA','SUBSTITUIDA','ENCERRADA')),
  CONSTRAINT garantias_datas_chk  CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

-- Art. 37, § único: é VEDADA mais de uma modalidade de garantia num mesmo
-- contrato (e exigir duas é contravenção penal — art. 43, II). O índice
-- parcial faz o próprio banco impedir isso.
CREATE UNIQUE INDEX uq_garantia_ativa_por_contrato
  ON public.garantias (contrato_id) WHERE status = 'ATIVA';
CREATE INDEX idx_garantias_contrato ON public.garantias (contrato_id);
CREATE TRIGGER trg_garantias_updated BEFORE UPDATE ON public.garantias
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CAUÇÃO (art. 38) -----------------------------------------------------
CREATE TABLE public.garantia_caucao (
  garantia_id       bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  modalidade        text NOT NULL,          -- DINHEIRO | BEM_MOVEL | BEM_IMOVEL | TITULOS
  valor             numeric(12,2) NULL,     -- obrigatório quando DINHEIRO
  -- Dinheiro → caderneta de poupança (art. 38, §2º)
  banco             text NULL,
  agencia           text NULL,
  conta_poupanca    text NULL,
  data_deposito     date NULL,
  comprovante_deposito_key text NULL, -- chave do objeto no S3 privado (nunca URL pública)
  -- Bens (art. 38, §1º): móvel → registro em RTD; imóvel → averbação na matrícula
  descricao_bem     text NULL,
  registro_cartorio text NULL,
  -- Devolução (os rendimentos revertem ao locatário — art. 38, §2º)
  valor_devolvido   numeric(12,2) NULL,
  valor_retido      numeric(12,2) NULL,
  motivo_retencao   text NULL,
  data_devolucao    date NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT caucao_modalidade_chk CHECK (modalidade IN ('DINHEIRO','BEM_MOVEL','BEM_IMOVEL','TITULOS')),
  CONSTRAINT caucao_dinheiro_chk   CHECK (modalidade <> 'DINHEIRO' OR valor IS NOT NULL),
  CONSTRAINT caucao_bem_chk        CHECK (modalidade = 'DINHEIRO' OR descricao_bem IS NOT NULL),
  CONSTRAINT caucao_valores_chk    CHECK (
    (valor           IS NULL OR valor           >= 0) AND
    (valor_devolvido IS NULL OR valor_devolvido >= 0) AND
    (valor_retido    IS NULL OR valor_retido    >= 0)
  ),
  CONSTRAINT caucao_retencao_chk   CHECK (
    valor_retido IS NULL OR valor_retido = 0 OR motivo_retencao IS NOT NULL
  )
);
CREATE TRIGGER trg_garantia_caucao_updated BEFORE UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Art. 38, §2º: caução EM DINHEIRO não pode exceder 3 meses de aluguel.
-- Regra cross-table (garantia_caucao → garantias → contratos), logo não cabe
-- num CHECK. O service valida com mensagem amigável; este trigger é a rede de
-- segurança no banco, porque o excesso torna a cláusula nula.
CREATE OR REPLACE FUNCTION valida_caucao_dinheiro()
RETURNS TRIGGER AS $$
DECLARE
  v_aluguel numeric(12,2);
BEGIN
  IF NEW.modalidade = 'DINHEIRO' THEN
    SELECT c.valor_aluguel
      INTO v_aluguel
      FROM public.garantias g
      JOIN public.contratos c ON c.id = g.contrato_id
     WHERE g.id = NEW.garantia_id;

    IF v_aluguel IS NOT NULL AND NEW.valor > (3 * v_aluguel) THEN
      RAISE EXCEPTION
        'Caucao em dinheiro nao pode exceder 3 alugueis (Lei 8.245/91, art. 38, §2º). Maximo: %, informado: %',
        (3 * v_aluguel), NEW.valor
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_caucao_limite_legal
  BEFORE INSERT OR UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION valida_caucao_dinheiro();

-- FIADORES (art. 40 + CC arts. 818-839) -------------------------------
CREATE TABLE public.garantia_fiadores (
  garantia_id                 bigint NOT NULL REFERENCES public.garantias(id) ON DELETE CASCADE,
  usuario_id                  bigint NOT NULL REFERENCES public.usuarios(id)  ON DELETE RESTRICT,
  -- Capacidade financeira (praxe: renda ≥ 3x o aluguel)
  renda_comprovada            numeric(12,2) NULL,
  comprovante_renda_key       text NULL,   -- chave do objeto no S3 privado (nunca URL pública)
  -- Imóvel dado em garantia. O bem de família do fiador é penhorável
  -- (Lei 8.009/90, art. 3º, VII). NÃO vira linha em `imoveis`, que é a tabela
  -- de imóvel PARA LOCAÇÃO (valor_aluguel_referencia, status DISPONIVEL...).
  imovel_garantia_endereco_id bigint NULL REFERENCES public.enderecos(id) ON DELETE SET NULL,
  imovel_garantia_matricula   text NULL,
  imovel_garantia_quitado     boolean NULL,
  -- Outorga conjugal (CC art. 1.647, III): sem ela, a fiança prestada por pessoa
  -- casada é ANULÁVEL — exceto no regime de separação absoluta.
  estado_civil                text NULL,
  regime_bens                 text NULL,
  conjuge_nome                text NULL,
  conjuge_documento           text NULL,
  outorga_conjugal            boolean NOT NULL DEFAULT false,
  -- Exoneração (art. 40, X): o fiador segue responsável por 120 dias após notificar.
  status                      text NOT NULL DEFAULT 'ATIVO',   -- ATIVO | EXONERADO
  data_notificacao_exoneracao date NULL,
  data_fim_responsabilidade   date NULL,                       -- notificação + 120 dias
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (garantia_id, usuario_id),
  CONSTRAINT fiador_status_chk       CHECK (status IN ('ATIVO','EXONERADO')),
  CONSTRAINT fiador_estado_civil_chk CHECK (
    estado_civil IS NULL OR
    estado_civil IN ('SOLTEIRO','CASADO','DIVORCIADO','VIUVO','UNIAO_ESTAVEL')
  ),
  CONSTRAINT fiador_regime_bens_chk  CHECK (
    regime_bens IS NULL OR
    regime_bens IN ('COMUNHAO_PARCIAL','COMUNHAO_UNIVERSAL','SEPARACAO_ABSOLUTA','PARTICIPACAO_FINAL')
  ),
  CONSTRAINT fiador_renda_chk        CHECK (renda_comprovada IS NULL OR renda_comprovada >= 0),
  CONSTRAINT fiador_outorga_chk      CHECK (
    estado_civil IS DISTINCT FROM 'CASADO'
    OR regime_bens = 'SEPARACAO_ABSOLUTA'
    OR outorga_conjugal = true
  ),
  CONSTRAINT fiador_exoneracao_chk   CHECK (
    status <> 'EXONERADO'
    OR (data_notificacao_exoneracao IS NOT NULL AND data_fim_responsabilidade IS NOT NULL)
  )
);
CREATE INDEX idx_garantia_fiador_usuario ON public.garantia_fiadores (usuario_id);
CREATE TRIGGER trg_garantia_fiadores_updated BEFORE UPDATE ON public.garantia_fiadores
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SEGURO FIANÇA (art. 41) ---------------------------------------------
-- A análise de crédito e o sinistro rodam na SEGURADORA, fora deste sistema.
-- Aqui só se registra que a apólice existe, foi aprovada e está vigente.
CREATE TABLE public.garantia_seguro_fianca (
  garantia_id          bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  seguradora           text NOT NULL,
  numero_apolice       text NOT NULL,
  vigencia_inicio      date NOT NULL,
  vigencia_fim         date NOT NULL,
  valor_cobertura      numeric(12,2) NOT NULL,   -- art. 41: totalidade das obrigações do locatário
  valor_premio         numeric(12,2) NULL,       -- o que o inquilino paga à seguradora
  periodicidade_premio text NULL,                -- MENSAL | ANUAL
  status_aprovacao     text NOT NULL DEFAULT 'PENDENTE',  -- PENDENTE | APROVADA | REJEITADA
  apolice_key          text NULL,                -- PDF da apólice no S3 privado
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seguro_status_chk        CHECK (status_aprovacao IN ('PENDENTE','APROVADA','REJEITADA')),
  CONSTRAINT seguro_periodicidade_chk CHECK (periodicidade_premio IS NULL OR periodicidade_premio IN ('MENSAL','ANUAL')),
  CONSTRAINT seguro_vigencia_chk      CHECK (vigencia_fim > vigencia_inicio),
  CONSTRAINT seguro_valores_chk       CHECK (
    valor_cobertura >= 0 AND (valor_premio IS NULL OR valor_premio >= 0)
  ),
  CONSTRAINT uq_seguro_apolice        UNIQUE (seguradora, numero_apolice)
);
CREATE TRIGGER trg_garantia_seguro_updated BEFORE UPDATE ON public.garantia_seguro_fianca
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Histórico de reajustes ----------------------------------------------
CREATE TABLE public.reajustes (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id         bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  data_reajuste       date   NOT NULL,
  valor_anterior      numeric(12,2) NOT NULL,
  valor_novo          numeric(12,2) NOT NULL,
  indice_aplicado     text   NOT NULL,
  percentual_aplicado numeric(6,3) NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_reajustes_contrato ON public.reajustes (contrato_id);

-- =====================================================================
-- BLOCO 4 — COBRANÇA E PAGAMENTO
-- =====================================================================

CREATE TABLE public.parcelas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id     bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  competencia     date   NOT NULL,             -- 1º dia do mês de referência
  data_vencimento date   NOT NULL,
  valor_base      numeric(12,2) NOT NULL,
  status          text   NOT NULL DEFAULT 'ABERTA',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT parcelas_status_chk CHECK (status IN ('ABERTA','PAGA','PARCIAL','VENCIDA','CANCELADA')),
  CONSTRAINT parcelas_valor_chk  CHECK (valor_base >= 0),
  CONSTRAINT parcelas_unica_por_competencia UNIQUE (contrato_id, competencia)
);
CREATE TRIGGER trg_parcelas_updated BEFORE UPDATE ON public.parcelas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_parcelas_contrato ON public.parcelas (contrato_id);
CREATE INDEX idx_parcelas_status   ON public.parcelas (status);
CREATE INDEX idx_parcelas_vencidas
  ON public.parcelas (data_vencimento) WHERE status IN ('ABERTA','VENCIDA');

-- Itens que compõem a parcela (aluguel, condomínio, multa, juros, desconto...)
CREATE TABLE public.parcela_lancamentos (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  tipo       text   NOT NULL,
  descricao  text   NULL,
  valor      numeric(12,2) NOT NULL,           -- >0 cobrança, <0 desconto
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lancamento_tipo_chk CHECK (
    tipo IN ('ALUGUEL','CONDOMINIO','IPTU','MULTA','JUROS','DESCONTO','TAXA','OUTRO')
  )
);
CREATE INDEX idx_lancamentos_parcela ON public.parcela_lancamentos (parcela_id);

-- Boletos emitidos para a parcela (suporta 2ª via) --------------------
CREATE TABLE public.boletos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id      bigint  NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  via             int     NOT NULL DEFAULT 1,
  nosso_numero    text    NULL,
  linha_digitavel text    NULL,
  codigo_barras   text    NULL,
  data_emissao    date    NOT NULL DEFAULT CURRENT_DATE,
  data_vencimento date    NOT NULL,
  valor           numeric(12,2) NOT NULL,
  ativo           boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT boletos_valor_chk CHECK (valor >= 0)
);
CREATE UNIQUE INDEX uq_boleto_ativo_por_parcela
  ON public.boletos (parcela_id) WHERE ativo;
CREATE INDEX idx_boletos_parcela ON public.boletos (parcela_id);

-- Pagamentos (múltiplos por parcela => pagamento parcial) -------------
CREATE TABLE public.pagamentos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id      bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE RESTRICT,
  boleto_id       bigint NULL REFERENCES public.boletos(id) ON DELETE SET NULL,
  valor_pago      numeric(12,2) NOT NULL,
  data_pagamento  date   NOT NULL DEFAULT CURRENT_DATE,
  forma_pagamento text   NOT NULL,
  comprovante_url text   NULL,
  registrado_por  bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pagamentos_forma_chk CHECK (
    forma_pagamento IN ('PIX','BOLETO','TRANSFERENCIA','DINHEIRO','CARTAO')
  ),
  CONSTRAINT pagamentos_valor_chk CHECK (valor_pago > 0)
);
CREATE INDEX idx_pagamentos_parcela ON public.pagamentos (parcela_id);

-- =====================================================================
-- OPCIONAL — triggers de regra de negócio, geração de parcelas e
-- multi-tenant: ver comentários da versão anterior. A estrutura não muda.
-- =====================================================================

-- Ajuste aplicado após a criação inicial: garante 1 código de
-- verificação ativo por usuário, necessário para o upsert em
-- UsersRepository.saveVerifyUserCode (onConflict: 'usuario_id').
alter table public.codigo_verificacao
  add constraint codigo_verificacao_usuario_id_key unique (usuario_id);
