-- =====================================================================
-- SISTEMA DE GERENCIAMENTO DE ALUGUÉIS — MODELO REFATORADO (PostgreSQL)
-- Variante: PESSOA + USUÁRIO em uma única tabela (`usuarios`)
-- =====================================================================
-- Convenções:
--   - PK bigint identity (compatível com o schema atual).
--   - Dinheiro em numeric(12,2). Nunca float.
--   - Enums via text + CHECK. Troque por CREATE TYPE ... AS ENUM se
--     quiser tipagem forte no banco.
--   - `usuarios` guarda cadastro + autenticação. senha_hash/perfil são
--     NULL para quem não loga (proprietário, fiador). A identidade real
--     da linha é `documento`. Papéis de negócio (proprietário/inquilino/
--     fiador) são RELACIONAMENTOS, nunca colunas booleanas.
-- =====================================================================

-- =====================================================================
-- RESET — apaga TODAS as tabelas deste modelo (e TODOS os dados!).
-- Destrutivo e irreversível. Roda antes de recriar tudo do zero.
-- CASCADE derruba FKs, índices e triggers dependentes junto.
-- =====================================================================
DROP TABLE IF EXISTS
  public.movimentacoes_financeiras,
  public.webhook_events,
  public.repasses,
  public.splits,
  public.gateway_cobrancas,
  public.contas_gateway,
  public.gateway_customers,
  public.pagamentos,
  public.boletos,
  public.parcela_lancamentos,
  public.parcelas,
  public.reajustes,
  public.garantia_seguro_fianca,
  public.garantia_fiadores,
  public.garantia_caucao,
  public.garantias,
  public.contrato_fiadores,   -- substituída por garantia_fiadores (migration 001)
  public.contrato_inquilinos,
  public.contratos,
  public.imoveis,
  public.contas_bancarias,
  public.codigo_verificacao,
  public.usuarios,
  public.pessoas,          -- caso exista de uma versão anterior do modelo
  public.enderecos
CASCADE;

DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS public.valida_caucao_dinheiro() CASCADE;
DROP FUNCTION IF EXISTS public.assert_contrato_tem_um_principal(bigint) CASCADE;
DROP FUNCTION IF EXISTS public.valida_principal_apos_contrato() CASCADE;
DROP FUNCTION IF EXISTS public.valida_principal_apos_vinculo() CASCADE;

-- =====================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- BLOCO 1 — ENDEREÇOS, USUÁRIOS/PESSOAS E ACESSO
-- =====================================================================

CREATE TABLE public.enderecos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pais         text    NOT NULL DEFAULT 'Brasil',
  cep          text    NOT NULL,
  estado       char(2) NOT NULL,
  cidade       text    NOT NULL,
  bairro       text    NOT NULL,
  logradouro   text    NOT NULL,
  numero       text    NULL,
  complemento  text    NULL,
  latitude     numeric(10,7) NULL,
  longitude    numeric(10,7) NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_enderecos_updated BEFORE UPDATE ON public.enderecos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- USUARIOS = cadastro (party) + autenticação, numa tabela só ----------
CREATE TABLE public.usuarios (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Cadastro (todo proprietário, inquilino, fiador e corretor é uma linha aqui)
  nome_completo     text    NOT NULL,          -- razão social se PJ
  documento         text    NOT NULL,          -- CPF/CNPJ: só dígitos
  -- Derivado do documento: 14 dígitos = CNPJ = PJ; senão PF
  tipo_pessoa       text    GENERATED ALWAYS AS (
                      CASE WHEN length(documento) = 14 THEN 'PJ' ELSE 'PF' END
                    ) STORED,
  rg                text    NULL,              -- RG (PF); opcional
  email             text    NULL,              -- contato + login
  telefone          text    NULL,
  telefone_fixo     text    NULL,              -- distinto do celular p/ gateway de pagamento (Asaas phone vs mobilePhone)
  data_nascimento   date    NULL,
  endereco_id       bigint  NULL REFERENCES public.enderecos(id) ON DELETE SET NULL,
  -- Dados exigidos pelo gateway de pagamento ao abrir subconta do proprietário
  -- (migration 004). NULL até esse momento; validados no service, não aqui.
  renda_mensal      numeric(12,2) NULL,
  tipo_empresa      text    NULL,              -- MEI|LIMITED|INDIVIDUAL|ASSOCIATION (obrigatório se PJ)
  -- Autenticação (NULL para quem não loga)
  senha_hash        text    NULL,
  perfil            text    NULL,              -- ADMIN/CORRETOR/CLIENTE
  email_verificado  boolean NOT NULL DEFAULT false,
  ultimo_login      timestamptz NULL,
  ativo             boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_documento_key UNIQUE (documento),
  CONSTRAINT usuarios_email_key     UNIQUE (email),
  CONSTRAINT usuarios_telefone_key  UNIQUE (telefone),
  CONSTRAINT usuarios_doc_chk    CHECK (documento ~ '^[0-9]+$' AND length(documento) IN (11,14)),
  CONSTRAINT usuarios_perfil_chk CHECK (perfil IS NULL OR perfil IN ('ADMIN','CORRETOR','CLIENTE')),
  CONSTRAINT usuarios_login_chk  CHECK (senha_hash IS NULL OR email IS NOT NULL),
  CONSTRAINT usuarios_tipo_empresa_chk CHECK (
    tipo_empresa IS NULL OR tipo_empresa IN ('MEI','LIMITED','INDIVIDUAL','ASSOCIATION')
  ),
  CONSTRAINT usuarios_renda_chk CHECK (renda_mensal IS NULL OR renda_mensal >= 0)
);
CREATE TRIGGER trg_usuarios_updated BEFORE UPDATE ON public.usuarios
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CODIGO_VERIFICACAO (PK própria, tipo, uso, histórico) ---------------
CREATE TABLE public.codigo_verificacao (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id  bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  codigo      text   NOT NULL,
  tipo        text   NOT NULL DEFAULT 'VERIFICACAO_EMAIL',
  expires_at  timestamptz NULL,
  usado_em    timestamptz NULL,
  tentativas_falhas int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT codigo_tipo_chk CHECK (tipo IN ('VERIFICACAO_EMAIL','RESET_SENHA')),
  CONSTRAINT codigo_tentativas_chk CHECK (tentativas_falhas >= 0)
);
CREATE UNIQUE INDEX uq_codigo_usuario_tipo
  ON public.codigo_verificacao (usuario_id, tipo);

-- CONTAS_BANCARIAS (do usuário/pessoa que recebe o aluguel) -----------
CREATE TABLE public.contas_bancarias (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id       bigint  NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  banco            text    NOT NULL,
  agencia          text    NOT NULL,
  conta            text    NOT NULL,
  digito           text    NULL,
  tipo_conta       text    NOT NULL,
  chave_pix        text    NULL,
  pix_key_type     text    NULL,   -- CPF|CNPJ|EMAIL|TELEFONE|ALEATORIA
  -- Tem que bater com o titular da subconta no gateway, senão o saque é
  -- recusado (migration 004). Validado no cadastro, não na hora do saque.
  cpf_cnpj_titular text    NULL,
  principal        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conta_pix_type_chk CHECK (
    pix_key_type IS NULL OR pix_key_type IN ('CPF','CNPJ','EMAIL','TELEFONE','ALEATORIA')
  ),
  CONSTRAINT conta_pix_par_chk CHECK (chave_pix IS NULL OR pix_key_type IS NOT NULL),
  CONSTRAINT conta_cpf_titular_chk CHECK (
    cpf_cnpj_titular IS NULL
    OR (cpf_cnpj_titular ~ '^[0-9]+$' AND length(cpf_cnpj_titular) IN (11,14))
  )
);
CREATE UNIQUE INDEX uq_conta_principal_por_usuario
  ON public.contas_bancarias (usuario_id) WHERE principal;

-- =====================================================================
-- BLOCO 2 — IMÓVEIS
-- =====================================================================

CREATE TABLE public.imoveis (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_referencia         text NULL,
  endereco_id               bigint NOT NULL REFERENCES public.enderecos(id) ON DELETE RESTRICT,
  -- Único responsável (proprietário) pelo imóvel.
  proprietario_id           bigint NULL REFERENCES public.usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tipo_imovel               text   NOT NULL,
  valor_aluguel_referencia  numeric(12,2) NOT NULL,
  valor_condominio          numeric(12,2) NULL,
  valor_iptu                numeric(12,2) NULL,
  area_util                 numeric(10,2) NULL,
  quartos                   int NULL,
  banheiros                 int NULL,
  vagas_garagem             int NULL,
  matricula                 text NULL,
  inscricao_iptu            text NULL,
  observacoes               text NULL,
  status                    text NOT NULL DEFAULT 'DISPONIVEL',
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT imoveis_status_chk CHECK (status IN ('DISPONIVEL','ALUGADO','MANUTENCAO','INATIVO')),
  CONSTRAINT imoveis_tipo_chk   CHECK (tipo_imovel IN ('CASA','APARTAMENTO','COMERCIAL','TERRENO','GALPAO','OUTRO')),
  CONSTRAINT imoveis_valor_chk  CHECK (valor_aluguel_referencia >= 0)
);
CREATE TRIGGER trg_imoveis_updated BEFORE UPDATE ON public.imoveis
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_imoveis_proprietario ON public.imoveis (proprietario_id);
CREATE UNIQUE INDEX uq_imoveis_numero_referencia
  ON public.imoveis (numero_referencia) WHERE numero_referencia IS NOT NULL;

-- Obs.: o vínculo imóvel ↔ proprietário deixou de ser N:N.
-- Agora há um único responsável por imóvel em imoveis.proprietario_id.

-- =====================================================================
-- BLOCO 3 — CONTRATOS
-- =====================================================================

CREATE TABLE public.contratos (
  id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imovel_id                     bigint NOT NULL REFERENCES public.imoveis(id) ON DELETE RESTRICT,
  proprietario_id_snapshot      bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  corretor_id                   bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  data_inicio                   date   NOT NULL,
  data_fim                      date   NOT NULL,
  valor_aluguel                 numeric(12,2) NOT NULL,
  dia_vencimento                int    NOT NULL,
  indice_reajuste               text   NOT NULL DEFAULT 'IGPM',
  periodicidade_reajuste_meses  int    NOT NULL DEFAULT 12,
  percentual_multa_atraso       numeric(5,2) NOT NULL DEFAULT 2,
  percentual_juros_mora_mensal  numeric(5,2) NOT NULL DEFAULT 1,
  dias_tolerancia               int    NOT NULL DEFAULT 0,
  taxa_administracao_percentual numeric(5,2) NOT NULL DEFAULT 0,
  -- Art. 39: a garantia se estende até a DEVOLUÇÃO EFETIVA do imóvel, que pode
  -- ocorrer depois de data_fim (locação prorrogada por prazo indeterminado).
  data_devolucao_imovel         date   NULL,
  -- Cobrança/repasse (migration 004) -----------------------------------
  forma_pagamento_padrao        text   NOT NULL DEFAULT 'INDEFINIDO',
  -- Dias de antecedência com que o cron gera a parcela antes do vencimento.
  dia_geracao_antecipada        int    NOT NULL DEFAULT 5,
  -- taxa_administracao_percentual (acima) é o valor quando comissao_tipo =
  -- 'PERCENTUAL', e incide sobre o ALUGUEL, não sobre o total da parcela.
  comissao_tipo                 text   NOT NULL DEFAULT 'PERCENTUAL',
  comissao_valor_fixo           numeric(12,2) NULL,
  -- Handoff durável para retomada do lote inicial após restart.
  cobrancas_iniciais_iniciadas_em  timestamptz NOT NULL DEFAULT now(),
  cobrancas_iniciais_a_partir_de   date NOT NULL DEFAULT CURRENT_DATE,
  cobrancas_iniciais_concluidas_em timestamptz NULL,
  migrado                       boolean NOT NULL DEFAULT false,
  status                        text   NOT NULL DEFAULT 'ATIVO',
  observacoes                   text   NULL,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now(),
  -- RASCUNHO: contrato montado, ainda não gera cobrança. SUSPENSO: cobrança
  -- temporariamente interrompida (acordo, disputa).
  CONSTRAINT contratos_status_chk    CHECK (
    status IN ('RASCUNHO','ATIVO','SUSPENSO','ENCERRADO','RESCINDIDO','INADIMPLENTE')
  ),
  CONSTRAINT contratos_indice_chk    CHECK (indice_reajuste IN ('IGPM','IPCA','INPC','FIXO')),
  CONSTRAINT contratos_dia_venc_chk  CHECK (dia_vencimento BETWEEN 1 AND 28),
  CONSTRAINT contratos_valor_chk     CHECK (valor_aluguel > 0),
  CONSTRAINT contratos_datas_chk     CHECK (data_fim > data_inicio),
  -- Lei 10.192/2001: reajuste com periodicidade mínima anual.
  CONSTRAINT contratos_reajuste_chk  CHECK (periodicidade_reajuste_meses >= 12),
  CONSTRAINT contratos_pct_chk       CHECK (
      percentual_multa_atraso       BETWEEN 0 AND 100 AND
      percentual_juros_mora_mensal  BETWEEN 0 AND 100 AND
      taxa_administracao_percentual BETWEEN 0 AND 100
  ),
  CONSTRAINT contratos_forma_pgto_chk CHECK (
    forma_pagamento_padrao IN ('BOLETO','PIX','CARTAO','INDEFINIDO')
  ),
  CONSTRAINT contratos_comissao_tipo_chk CHECK (comissao_tipo IN ('PERCENTUAL','FIXO')),
  -- Comissão FIXA sem valor definido deixaria o repasse indeterminado.
  CONSTRAINT contratos_comissao_valor_chk CHECK (
    comissao_tipo <> 'FIXO' OR comissao_valor_fixo IS NOT NULL
  ),
  CONSTRAINT contratos_geracao_chk CHECK (dia_geracao_antecipada BETWEEN 0 AND 28)
);

-- Obs.: a garantia NÃO fica mais em `contratos` (tipo_garantia/valor_caucao foram
-- removidos na migration 001). Ela vive no BLOCO 3.1, e a ausência de garantia
-- ATIVA significa locação sem garantia (art. 42 da Lei 8.245/91).
CREATE TRIGGER trg_contratos_updated BEFORE UPDATE ON public.contratos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Um imóvel não pode ter dois contratos ATIVOS com períodos sobrepostos
ALTER TABLE public.contratos
  ADD CONSTRAINT contratos_sem_sobreposicao
  EXCLUDE USING gist (
    imovel_id WITH =,
    daterange(data_inicio, data_fim, '[]') WITH &&
  ) WHERE (status IN ('ATIVO', 'INADIMPLENTE'));

CREATE INDEX idx_contratos_imovel   ON public.contratos (imovel_id);
CREATE INDEX idx_contratos_status   ON public.contratos (status);
CREATE INDEX idx_contratos_data_fim ON public.contratos (data_fim);

-- N:N contrato ↔ inquilinos -------------------------------------------
CREATE TABLE public.contrato_inquilinos (
  contrato_id bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  usuario_id  bigint NOT NULL REFERENCES public.usuarios(id)  ON DELETE RESTRICT,
  principal   boolean NOT NULL DEFAULT false,
  PRIMARY KEY (contrato_id, usuario_id)
);
CREATE INDEX idx_contrato_inq_usuario ON public.contrato_inquilinos (usuario_id);
CREATE UNIQUE INDEX uq_inquilino_principal
  ON public.contrato_inquilinos (contrato_id) WHERE principal;

-- O índice acima garante "no máximo um". Os gatilhos diferidos abaixo
-- garantem "exatamente um" no COMMIT, permitindo criar o contrato e inserir
-- seus vínculos (ou substituir os vínculos) dentro da mesma transação.
CREATE OR REPLACE FUNCTION public.assert_contrato_tem_um_principal(
  p_contrato_id bigint
)
RETURNS void AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.contratos WHERE id = p_contrato_id)
     AND (
       SELECT count(*)
       FROM public.contrato_inquilinos
       WHERE contrato_id = p_contrato_id AND principal
     ) <> 1 THEN
    RAISE EXCEPTION
      'O contrato % deve possuir exatamente um inquilino principal.',
      p_contrato_id
      USING ERRCODE = '23514';
  END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.valida_principal_apos_contrato()
RETURNS trigger AS $$
BEGIN
  PERFORM public.assert_contrato_tem_um_principal(NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.valida_principal_apos_vinculo()
RETURNS trigger AS $$
BEGIN
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    PERFORM public.assert_contrato_tem_um_principal(NEW.contrato_id);
  END IF;
  IF TG_OP = 'DELETE'
     OR (TG_OP = 'UPDATE' AND OLD.contrato_id <> NEW.contrato_id) THEN
    PERFORM public.assert_contrato_tem_um_principal(OLD.contrato_id);
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER contratos_exigem_inquilino_principal
AFTER INSERT OR UPDATE ON public.contratos
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.valida_principal_apos_contrato();

CREATE CONSTRAINT TRIGGER contrato_inquilinos_exatamente_um_principal
AFTER INSERT OR UPDATE OR DELETE ON public.contrato_inquilinos
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.valida_principal_apos_vinculo();

-- =====================================================================
-- BLOCO 3.1 — GARANTIAS LOCATÍCIAS (Lei 8.245/91, arts. 37 a 42)
-- =====================================================================
-- Modelo supertipo + detalhe. A modalidade da garantia é um RELACIONAMENTO,
-- nunca uma coluna solta em `contratos`.
--
--   garantias
--     ├── garantia_caucao         (1:1)
--     ├── garantia_fiadores       (1:N)
--     └── garantia_seguro_fianca  (1:1)
--
-- Ausência de garantia ATIVA = locação sem garantia (art. 42: nesse caso o
-- locador pode exigir o aluguel até o 6º dia útil do mês vincendo).
-- =====================================================================

CREATE TABLE public.garantias (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id         bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  tipo                text   NOT NULL,                   -- CAUCAO | FIADOR | SEGURO_FIANCA
  status              text   NOT NULL DEFAULT 'ATIVA',   -- ATIVA | SUBSTITUIDA | ENCERRADA
  data_inicio         date   NOT NULL DEFAULT CURRENT_DATE,
  data_fim            date   NULL,                       -- preenchida ao substituir/encerrar
  motivo_substituicao text   NULL,                       -- art. 40
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT garantias_tipo_chk   CHECK (tipo IN ('CAUCAO','FIADOR','SEGURO_FIANCA')),
  CONSTRAINT garantias_status_chk CHECK (status IN ('ATIVA','SUBSTITUIDA','ENCERRADA')),
  CONSTRAINT garantias_datas_chk  CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

-- Art. 37, § único: é VEDADA mais de uma modalidade de garantia num mesmo
-- contrato (e exigir duas é contravenção penal — art. 43, II). O índice
-- parcial faz o próprio banco impedir isso.
CREATE UNIQUE INDEX uq_garantia_ativa_por_contrato
  ON public.garantias (contrato_id) WHERE status = 'ATIVA';
CREATE INDEX idx_garantias_contrato ON public.garantias (contrato_id);
CREATE TRIGGER trg_garantias_updated BEFORE UPDATE ON public.garantias
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CAUÇÃO (art. 38) -----------------------------------------------------
CREATE TABLE public.garantia_caucao (
  garantia_id       bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  modalidade        text NOT NULL,          -- DINHEIRO | BEM_MOVEL | BEM_IMOVEL | TITULOS
  valor             numeric(12,2) NULL,     -- obrigatório quando DINHEIRO
  -- Dinheiro → caderneta de poupança (art. 38, §2º)
  banco             text NULL,
  agencia           text NULL,
  conta_poupanca    text NULL,
  data_deposito     date NULL,
  comprovante_deposito_key text NULL, -- chave do objeto no S3 privado (nunca URL pública)
  status_pagamento text NOT NULL DEFAULT 'PENDENTE',
  pago_em         timestamptz NULL,
  analisado_por   bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  analisado_em    timestamptz NULL,
  -- Bens (art. 38, §1º): móvel → registro em RTD; imóvel → averbação na matrícula
  descricao_bem     text NULL,
  registro_cartorio text NULL,
  -- Devolução (os rendimentos revertem ao locatário — art. 38, §2º)
  valor_devolvido   numeric(12,2) NULL,
  valor_retido      numeric(12,2) NULL,
  motivo_retencao   text NULL,
  data_devolucao    date NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT caucao_modalidade_chk CHECK (modalidade IN ('DINHEIRO','BEM_MOVEL','BEM_IMOVEL','TITULOS')),
  CONSTRAINT caucao_dinheiro_chk   CHECK (modalidade <> 'DINHEIRO' OR valor IS NOT NULL),
  CONSTRAINT caucao_bem_chk        CHECK (modalidade = 'DINHEIRO' OR descricao_bem IS NOT NULL),
  CONSTRAINT caucao_valores_chk    CHECK (
    (valor           IS NULL OR valor           >= 0) AND
    (valor_devolvido IS NULL OR valor_devolvido >= 0) AND
    (valor_retido    IS NULL OR valor_retido    >= 0)
  ),
  CONSTRAINT caucao_retencao_chk   CHECK (
    valor_retido IS NULL OR valor_retido = 0 OR motivo_retencao IS NOT NULL
  ),
  CONSTRAINT garantia_caucao_status_pagamento_chk CHECK (
    status_pagamento IN ('PENDENTE','EM_ANALISE','PAGO','REJEITADO')
  )
);
CREATE TRIGGER trg_garantia_caucao_updated BEFORE UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Art. 38, §2º: caução EM DINHEIRO não pode exceder 3 meses de aluguel.
-- Regra cross-table (garantia_caucao → garantias → contratos), logo não cabe
-- num CHECK. O service valida com mensagem amigável; este trigger é a rede de
-- segurança no banco, porque o excesso torna a cláusula nula.
CREATE OR REPLACE FUNCTION valida_caucao_dinheiro()
RETURNS TRIGGER AS $$
DECLARE
  v_aluguel numeric(12,2);
BEGIN
  IF NEW.modalidade = 'DINHEIRO' THEN
    SELECT c.valor_aluguel
      INTO v_aluguel
      FROM public.garantias g
      JOIN public.contratos c ON c.id = g.contrato_id
     WHERE g.id = NEW.garantia_id;

    IF v_aluguel IS NOT NULL AND NEW.valor > (3 * v_aluguel) THEN
      RAISE EXCEPTION
        'Caucao em dinheiro nao pode exceder 3 alugueis (Lei 8.245/91, art. 38, §2º). Maximo: %, informado: %',
        (3 * v_aluguel), NEW.valor
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_caucao_limite_legal
  BEFORE INSERT OR UPDATE ON public.garantia_caucao
  FOR EACH ROW EXECUTE FUNCTION valida_caucao_dinheiro();

-- FIADORES (art. 40 + CC arts. 818-839) -------------------------------
CREATE TABLE public.garantia_fiadores (
  garantia_id                 bigint NOT NULL REFERENCES public.garantias(id) ON DELETE CASCADE,
  usuario_id                  bigint NOT NULL REFERENCES public.usuarios(id)  ON DELETE RESTRICT,
  -- Capacidade financeira (praxe: renda ≥ 3x o aluguel)
  renda_comprovada            numeric(12,2) NULL,
  comprovante_renda_key       text NULL,   -- chave do objeto no S3 privado (nunca URL pública)
  certidao_imovel_key         text NULL,
  -- Imóvel dado em garantia. O bem de família do fiador é penhorável
  -- (Lei 8.009/90, art. 3º, VII). NÃO vira linha em `imoveis`, que é a tabela
  -- de imóvel PARA LOCAÇÃO (valor_aluguel_referencia, status DISPONIVEL...).
  imovel_garantia_endereco_id bigint NULL REFERENCES public.enderecos(id) ON DELETE SET NULL,
  imovel_garantia_matricula   text NULL,
  imovel_garantia_quitado     boolean NULL,
  -- Outorga conjugal (CC art. 1.647, III): sem ela, a fiança prestada por pessoa
  -- casada é ANULÁVEL — exceto no regime de separação absoluta.
  estado_civil                text NULL,
  regime_bens                 text NULL,
  conjuge_nome                text NULL,
  conjuge_documento           text NULL,
  outorga_conjugal            boolean NOT NULL DEFAULT false,
  -- Exoneração (art. 40, X): o fiador segue responsável por 120 dias após notificar.
  status                      text NOT NULL DEFAULT 'ATIVO',   -- ATIVO | EXONERADO
  data_notificacao_exoneracao date NULL,
  data_fim_responsabilidade   date NULL,                       -- notificação + 120 dias
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (garantia_id, usuario_id),
  CONSTRAINT fiador_status_chk       CHECK (status IN ('ATIVO','EXONERADO')),
  CONSTRAINT fiador_estado_civil_chk CHECK (
    estado_civil IS NULL OR
    estado_civil IN ('SOLTEIRO','CASADO','DIVORCIADO','VIUVO','UNIAO_ESTAVEL')
  ),
  CONSTRAINT fiador_regime_bens_chk  CHECK (
    regime_bens IS NULL OR
    regime_bens IN ('COMUNHAO_PARCIAL','COMUNHAO_UNIVERSAL','SEPARACAO_ABSOLUTA','PARTICIPACAO_FINAL')
  ),
  CONSTRAINT fiador_renda_chk        CHECK (renda_comprovada IS NULL OR renda_comprovada >= 0),
  CONSTRAINT fiador_outorga_chk      CHECK (
    estado_civil IS DISTINCT FROM 'CASADO'
    OR regime_bens = 'SEPARACAO_ABSOLUTA'
    OR outorga_conjugal = true
  ),
  CONSTRAINT fiador_exoneracao_chk   CHECK (
    status <> 'EXONERADO'
    OR (data_notificacao_exoneracao IS NOT NULL AND data_fim_responsabilidade IS NOT NULL)
  )
);
CREATE INDEX idx_garantia_fiador_usuario ON public.garantia_fiadores (usuario_id);
CREATE TRIGGER trg_garantia_fiadores_updated BEFORE UPDATE ON public.garantia_fiadores
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SEGURO FIANÇA (art. 41) ---------------------------------------------
-- A análise de crédito e o sinistro rodam na SEGURADORA, fora deste sistema.
-- Aqui só se registra que a apólice existe, foi aprovada e está vigente.
CREATE TABLE public.garantia_seguro_fianca (
  garantia_id          bigint PRIMARY KEY REFERENCES public.garantias(id) ON DELETE CASCADE,
  seguradora           text NOT NULL,
  numero_apolice       text NOT NULL,
  vigencia_inicio      date NOT NULL,
  vigencia_fim         date NOT NULL,
  valor_cobertura      numeric(12,2) NOT NULL,   -- art. 41: totalidade das obrigações do locatário
  valor_premio         numeric(12,2) NULL,       -- o que o inquilino paga à seguradora
  periodicidade_premio text NULL,                -- MENSAL | ANUAL
  status_aprovacao     text NOT NULL DEFAULT 'PENDENTE',  -- PENDENTE | APROVADA | REJEITADA
  apolice_key          text NULL,                -- PDF da apólice no S3 privado
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seguro_status_chk        CHECK (status_aprovacao IN ('PENDENTE','APROVADA','REJEITADA')),
  CONSTRAINT seguro_periodicidade_chk CHECK (periodicidade_premio IS NULL OR periodicidade_premio IN ('MENSAL','ANUAL')),
  CONSTRAINT seguro_vigencia_chk      CHECK (vigencia_fim > vigencia_inicio),
  CONSTRAINT seguro_valores_chk       CHECK (
    valor_cobertura >= 0 AND (valor_premio IS NULL OR valor_premio >= 0)
  ),
  CONSTRAINT uq_seguro_apolice        UNIQUE (seguradora, numero_apolice)
);
CREATE TRIGGER trg_garantia_seguro_updated BEFORE UPDATE ON public.garantia_seguro_fianca
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Histórico de reajustes ----------------------------------------------
CREATE TABLE public.reajustes (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id         bigint NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  data_reajuste       date   NOT NULL,
  valor_anterior      numeric(12,2) NOT NULL,
  valor_novo          numeric(12,2) NOT NULL,
  indice_aplicado     text   NOT NULL,
  percentual_aplicado numeric(6,3) NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_reajustes_contrato ON public.reajustes (contrato_id);

-- =====================================================================
-- BLOCO 4 — COBRANÇA E PAGAMENTO
-- =====================================================================

CREATE TABLE public.parcelas (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id        bigint NOT NULL REFERENCES public.contratos(id) ON DELETE RESTRICT,
  competencia        date   NOT NULL,             -- 1º dia do mês de referência
  data_vencimento    date   NOT NULL,
  valor_base         numeric(12,2) NOT NULL,
  status             text   NOT NULL DEFAULT 'ABERTA',
  -- Cobrança via gateway (migration 004) --------------------------------
  forma_pagamento    text   NULL,                 -- BOLETO|PIX|CARTAO
  external_reference text   NULL,                 -- chave devolvida nos webhooks do gateway
  -- Incrementa a cada reemissão (reajuste após emissão, correção de valor).
  -- Nunca deve haver duas cobranças ativas para a mesma parcela.
  tentativa          int    NOT NULL DEFAULT 1,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  -- PENDENTE: emitida no gateway, aguardando pagamento.
  -- CONFIRMADA: pagamento reconhecido, saldo AINDA NÃO liquidado.
  -- RECEBIDA: saldo disponível — único estado a partir do qual se repassa.
  -- REPASSADA: repasse ao proprietário concluído. ESTORNADA: estorno/chargeback.
  CONSTRAINT parcelas_status_chk CHECK (
    status IN ('ABERTA','PENDENTE','CONFIRMADA','RECEBIDA','PAGA','PARCIAL',
               'VENCIDA','REPASSADA','CANCELADA','ESTORNADA')
  ),
  CONSTRAINT parcelas_valor_chk  CHECK (valor_base >= 0),
  CONSTRAINT parcelas_unica_por_competencia UNIQUE (contrato_id, competencia),
  CONSTRAINT parcelas_forma_pgto_chk CHECK (
    forma_pagamento IS NULL OR forma_pagamento IN ('BOLETO','PIX','CARTAO')
  ),
  CONSTRAINT parcelas_tentativa_chk CHECK (tentativa >= 1)
);
CREATE TRIGGER trg_parcelas_updated BEFORE UPDATE ON public.parcelas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_parcelas_contrato ON public.parcelas (contrato_id);
CREATE INDEX idx_parcelas_status   ON public.parcelas (status);
CREATE INDEX idx_parcelas_contrato_vencimento
  ON public.parcelas (contrato_id, data_vencimento, id);
CREATE INDEX idx_parcelas_vencidas
  ON public.parcelas (data_vencimento) WHERE status IN ('ABERTA','VENCIDA');
-- Chave de conciliação com o gateway: dois registros com a mesma referência
-- tornariam o pagamento impossível de atribuir.
CREATE UNIQUE INDEX uq_parcela_external_reference
  ON public.parcelas (external_reference) WHERE external_reference IS NOT NULL;

-- Itens que compõem a parcela (aluguel, condomínio, multa, juros, desconto...)
CREATE TABLE public.parcela_lancamentos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id   bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  tipo         text   NOT NULL,
  descricao    text   NULL,
  valor        numeric(12,2) NOT NULL,           -- >0 cobrança, <0 desconto
  -- De quem é o lançamento — é daqui que o valor do split é derivado
  -- (migration 004): soma dos lançamentos com beneficiario='PROPRIETARIO'.
  -- A comissão entra como tipo='TAXA', beneficiario='IMOBILIARIA', valor
  -- negativo (desconto do proprietário, não cobrança do inquilino).
  beneficiario text   NOT NULL DEFAULT 'PROPRIETARIO',
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lancamento_tipo_chk CHECK (
    tipo IN ('ALUGUEL','CONDOMINIO','IPTU','MULTA','JUROS','DESCONTO','TAXA','OUTRO')
  ),
  CONSTRAINT lancamento_beneficiario_chk CHECK (beneficiario IN ('PROPRIETARIO','IMOBILIARIA'))
);
CREATE INDEX idx_lancamentos_parcela ON public.parcela_lancamentos (parcela_id);

-- Boletos emitidos para a parcela (histórico de vias) ------------------
-- Desde a migration 004, a cobrança ATIVA vive em `gateway_cobrancas`
-- (linha digitável, URL do boleto/Pix vindos do gateway, fonte da 2ª via).
-- Esta tabela fica como histórico de vias emitidas; não é mais escrita em
-- paralelo com gateway_cobrancas.
CREATE TABLE public.boletos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id      bigint  NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  via             int     NOT NULL DEFAULT 1,
  nosso_numero    text    NULL,
  linha_digitavel text    NULL,
  codigo_barras   text    NULL,
  data_emissao    date    NOT NULL DEFAULT CURRENT_DATE,
  data_vencimento date    NOT NULL,
  valor           numeric(12,2) NOT NULL,
  ativo           boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT boletos_valor_chk CHECK (valor >= 0)
);
CREATE UNIQUE INDEX uq_boleto_ativo_por_parcela
  ON public.boletos (parcela_id) WHERE ativo;
CREATE INDEX idx_boletos_parcela ON public.boletos (parcela_id);
COMMENT ON TABLE public.boletos IS
  'Histórico de vias emitidas. A cobrança ativa vive em gateway_cobrancas.';

-- Pagamentos (múltiplos por parcela => pagamento parcial) -------------
CREATE TABLE public.pagamentos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id       bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE RESTRICT,
  boleto_id        bigint NULL REFERENCES public.boletos(id) ON DELETE SET NULL,
  valor_pago       numeric(12,2) NOT NULL,
  data_pagamento   date   NOT NULL DEFAULT CURRENT_DATE,
  forma_pagamento  text   NOT NULL,
  comprovante_url  text   NULL,
  comprovante_key  text   NULL,
  registrado_por   bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  origem           text   NOT NULL DEFAULT 'GATEWAY',
  -- Webhook que originou este registro (migration 004), quando não for
  -- lançamento manual.
  gateway_event_id text   NULL,
  -- Mantém trilha do recebimento, mas o exclui do saldo após estorno.
  estornado_em     timestamptz NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pagamentos_forma_chk CHECK (
    forma_pagamento IN ('PIX','BOLETO','TRANSFERENCIA','DINHEIRO','CARTAO')
  ),
  CONSTRAINT pagamentos_valor_chk CHECK (valor_pago > 0),
  CONSTRAINT pagamentos_origem_chk CHECK (
    origem IN ('GATEWAY','PRESENCIAL','MIGRACAO')
  )
);
CREATE INDEX idx_pagamentos_parcela ON public.pagamentos (parcela_id);
CREATE UNIQUE INDEX uq_pagamento_gateway_event
  ON public.pagamentos (gateway_event_id) WHERE gateway_event_id IS NOT NULL;

-- =====================================================================
-- BLOCO 5 — INTEGRAÇÃO COM O GATEWAY DE PAGAMENTO (Asaas)
-- =====================================================================
-- migration 004. Ver docs/plano-financeiro-adaptado.md e
-- asaas-split-subcontas.md (repo frontend) para o desenho completo.
--
-- Desenhado em duas fases:
--   Fase 1 (MVP) — recebimento na conta principal; `contas_gateway` e
--     `splits` não são usadas; repasse manual/Pix registrado em `repasses`
--     com conta_gateway_id NULL.
--   Fase 2 — split automático via subconta do proprietário, liberado só
--     depois do período de avaliação regulatória do Banco Central
--     (Resolução Conjunta nº 16/17: até 10 subcontas, R$ 2.000 emitidos
--     por subconta, 60 dias).
-- =====================================================================

-- Locatário como "customer" no gateway ---------------------------------
CREATE TABLE public.gateway_customers (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id           bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  gateway              text   NOT NULL DEFAULT 'ASAAS',
  external_customer_id text   NOT NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_gateway_customer UNIQUE (usuario_id, gateway)
);
CREATE UNIQUE INDEX uq_gateway_customer_external
  ON public.gateway_customers (gateway, external_customer_id);

-- Subconta BaaS do proprietário — destino do split (Fase 2) ------------
-- Fluxo obrigatório de criação: (1) INSERT aqui com status='PENDENTE' e
-- external_reference próprio; (2) POST no gateway enviando essa referência;
-- (3) UPDATE com external_account_id/wallet_id/api_key_encrypted. A apiKey
-- da subconta é retornada UMA ÚNICA VEZ e não tem endpoint de recuperação —
-- se o passo 2 der certo e o 3 falhar, a external_reference permite
-- reconciliar em vez de criar outra subconta.
CREATE TABLE public.contas_gateway (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id          bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  gateway             text   NOT NULL DEFAULT 'ASAAS',
  external_reference  text   NOT NULL,
  external_account_id text   NULL,
  wallet_id           text   NULL,
  -- NUNCA em texto puro, nunca em log, nunca em resposta de API ao frontend.
  api_key_encrypted   text   NULL,
  status              text   NOT NULL DEFAULT 'PENDENTE',
  onboarding_status   text   NULL,
  onboarding_url      text   NULL,   -- link de envio de documentos (reenviável)
  aprovada_em         timestamptz NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_conta_gateway     UNIQUE (usuario_id, gateway),
  CONSTRAINT uq_conta_gateway_ref UNIQUE (gateway, external_reference),
  CONSTRAINT conta_gateway_status_chk CHECK (
    status IN ('PENDENTE','APROVADA','BLOQUEADA','RECUSADA')
  ),
  -- Só uma subconta APROVADA pode receber split, e para isso precisa da
  -- wallet e da chave — impede UPDATE parcial deixar o registro incompleto
  -- num estado que o código a jusante trataria como pronto.
  CONSTRAINT conta_gateway_aprovada_chk CHECK (
    status <> 'APROVADA'
    OR (external_account_id IS NOT NULL
        AND wallet_id IS NOT NULL
        AND api_key_encrypted IS NOT NULL)
  )
);
CREATE TRIGGER trg_contas_gateway_updated BEFORE UPDATE ON public.contas_gateway
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Espelho da parcela (cobrança) no gateway — fonte da verdade da 2ª via
CREATE TABLE public.gateway_cobrancas (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id          bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  gateway             text   NOT NULL DEFAULT 'ASAAS',
  external_payment_id text   NOT NULL,
  linha_digitavel     text   NULL,
  codigo_barras       text   NULL,
  url_boleto          text   NULL,
  url_fatura          text   NULL,
  qr_code_pix         text   NULL,
  copia_cola_pix      text   NULL,
  valor               numeric(12,2) NOT NULL,
  data_vencimento     date   NOT NULL,
  status_gateway      text   NULL,   -- vocabulário do gateway, sem tradução
  raw_json            jsonb  NULL,   -- resposta crua, para auditoria
  ativa               boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gateway_cobranca_valor_chk CHECK (valor >= 0)
);
-- Uma parcela acumula cobranças ao longo do tempo (reemissão por reajuste),
-- mas só UMA pode estar ativa — duas vivas significa cobrar em dobro.
CREATE UNIQUE INDEX uq_gateway_cobranca_ativa
  ON public.gateway_cobrancas (parcela_id) WHERE ativa;
CREATE UNIQUE INDEX uq_gateway_cobranca_external
  ON public.gateway_cobrancas (gateway, external_payment_id);
CREATE INDEX idx_gateway_cobranca_parcela ON public.gateway_cobrancas (parcela_id);
CREATE TRIGGER trg_gateway_cobrancas_updated BEFORE UPDATE ON public.gateway_cobrancas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Regra de split da parcela (Fase 2) -----------------------------------
-- Usar sempre tipo='FIXO', com valor derivado dos parcela_lancamentos do
-- proprietário. PERCENTUAL erra quando a parcela tem condomínio/IPTU/
-- desconto, e no Asaas incide sobre o valor LÍQUIDO — o proprietário
-- rateia a tarifa do gateway.
CREATE TABLE public.splits (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id        bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE CASCADE,
  conta_gateway_id  bigint NOT NULL REFERENCES public.contas_gateway(id) ON DELETE RESTRICT,
  tipo              text   NOT NULL DEFAULT 'FIXO',
  valor             numeric(12,2) NOT NULL,
  external_split_id text   NULL,
  status            text   NOT NULL DEFAULT 'PENDENTE',
  motivo_recusa     text   NULL,   -- refusalReason do gateway
  creditado_em      timestamptz NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT split_tipo_chk   CHECK (tipo IN ('FIXO','PERCENTUAL')),
  CONSTRAINT split_valor_chk  CHECK (valor >= 0),
  CONSTRAINT split_status_chk CHECK (
    status IN ('PENDENTE','AGUARDANDO_CREDITO','CONCLUIDO','CANCELADO','RECUSADO','ESTORNADO')
  ),
  CONSTRAINT split_recusa_chk CHECK (status <> 'RECUSADO' OR motivo_recusa IS NOT NULL)
);
CREATE INDEX idx_splits_parcela ON public.splits (parcela_id);
CREATE INDEX idx_splits_conta   ON public.splits (conta_gateway_id);
CREATE TRIGGER trg_splits_updated BEFORE UPDATE ON public.splits
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Repasse (subconta ou conta principal → banco do proprietário) --------
-- Serve às duas fases: Fase 1 usa conta_gateway_id NULL (sai da conta
-- principal); Fase 2 usa a subconta do proprietário.
-- Regra crítica: só disparar a partir de parcela em RECEBIDA (saldo
-- liquidado), nunca de CONFIRMADA. Na Fase 2, o gatilho é o split em
-- CONCLUIDO — no evento de pagamento recebido o split ainda pode estar em
-- AGUARDANDO_CREDITO e a transferência é recusada por saldo insuficiente.
CREATE TABLE public.repasses (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id           bigint NOT NULL REFERENCES public.parcelas(id) ON DELETE RESTRICT,
  conta_gateway_id     bigint NULL REFERENCES public.contas_gateway(id) ON DELETE RESTRICT,
  conta_bancaria_id    bigint NULL REFERENCES public.contas_bancarias(id) ON DELETE SET NULL,
  valor                numeric(12,2) NOT NULL,
  metodo               text   NOT NULL DEFAULT 'PIX',
  status               text   NOT NULL DEFAULT 'PROCESSANDO',
  external_transfer_id text   NULL,
  motivo_falha         text   NULL,
  comprovante_key      text   NULL,   -- objeto no S3 privado (padrão das garantias)
  tentativa            int    NOT NULL DEFAULT 1,
  solicitado_em        timestamptz NOT NULL DEFAULT now(),
  efetivado_em         timestamptz NULL,
  CONSTRAINT repasse_status_chk    CHECK (status IN ('PROCESSANDO','CONCLUIDO','FALHOU')),
  CONSTRAINT repasse_metodo_chk    CHECK (metodo IN ('PIX','TED','MANUAL')),
  CONSTRAINT repasse_valor_chk     CHECK (valor > 0),
  CONSTRAINT repasse_falha_chk     CHECK (status <> 'FALHOU' OR motivo_falha IS NOT NULL),
  CONSTRAINT repasse_efetivado_chk CHECK (status <> 'CONCLUIDO' OR efetivado_em IS NOT NULL)
);
-- Transferência duplicada é dinheiro que sai duas vezes e não volta sozinho:
-- só uma tentativa viva por parcela (uma que FALHOU pode ser refeita).
CREATE UNIQUE INDEX uq_repasse_ativo_por_parcela
  ON public.repasses (parcela_id) WHERE status <> 'FALHOU';
CREATE INDEX idx_repasses_conta_gateway ON public.repasses (conta_gateway_id);
CREATE INDEX idx_repasses_status        ON public.repasses (status);

-- Idempotência e trilha dos webhooks ------------------------------------
-- O endpoint é PÚBLICO (fora do authMiddleware) e o gateway reenvia
-- eventos. O UNIQUE abaixo impede registrar o mesmo pagamento duas vezes
-- ou disparar um repasse em duplicidade.
CREATE TABLE public.webhook_events (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway           text   NOT NULL DEFAULT 'ASAAS',
  external_event_id text   NOT NULL,
  event_type        text   NOT NULL,
  -- NULL para eventos da conta principal; preenchido para os de subconta,
  -- que chegam por rota própria (/webhooks/asaas/sub/:contaGatewayId).
  conta_gateway_id  bigint NULL REFERENCES public.contas_gateway(id) ON DELETE SET NULL,
  payload_json      jsonb  NOT NULL,
  status            text   NOT NULL DEFAULT 'RECEBIDO',
  tentativas        int    NOT NULL DEFAULT 0,
  proxima_tentativa_em timestamptz NOT NULL DEFAULT now(),
  erro_mensagem     text   NULL,
  recebido_em       timestamptz NOT NULL DEFAULT now(),
  processado_em     timestamptz NULL,
  descartado_em     timestamptz NULL,
  CONSTRAINT uq_webhook_event UNIQUE (gateway, external_event_id),
  CONSTRAINT webhook_status_chk CHECK (
    status IN ('RECEBIDO','PROCESSADO','ERRO','IGNORADO','DESCARTADO')
  ),
  CONSTRAINT webhook_tentativas_chk CHECK (tentativas >= 0)
);
CREATE INDEX idx_webhook_pendentes
  ON public.webhook_events (proxima_tentativa_em, recebido_em, id)
  WHERE status IN ('RECEBIDO','ERRO');

-- Livro-razão (ledger) para conciliação ----------------------------------
-- Trilha append-only: cada evento de dinheiro vira uma linha, e o estorno
-- entra como lançamento reverso em vez de UPDATE.
CREATE TABLE public.movimentacoes_financeiras (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id         bigint NULL REFERENCES public.parcelas(id) ON DELETE SET NULL,
  tipo               text   NOT NULL,
  valor              numeric(12,2) NOT NULL,   -- sinal indica entrada/saída
  origem             text   NULL,
  destino            text   NULL,
  referencia_externa text   NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mov_tipo_chk CHECK (
    tipo IN ('COBRANCA','PAGAMENTO','SPLIT','REPASSE','ESTORNO','TARIFA','COMISSAO')
  )
);
CREATE INDEX idx_mov_parcela ON public.movimentacoes_financeiras (parcela_id);
CREATE INDEX idx_mov_tipo    ON public.movimentacoes_financeiras (tipo, created_at);

-- =====================================================================
-- OPCIONAL — triggers de regra de negócio, geração de parcelas e
-- multi-tenant: ver comentários da versão anterior. A estrutura não muda.
-- =====================================================================

-- =====================================================================
-- BLOCO 7 — GESTÃO DOCUMENTAL, CAUÇÃO PIX E BAIXAS PRESENCIAIS
-- =====================================================================

CREATE TABLE public.caucao_cobrancas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garantia_id bigint NOT NULL REFERENCES public.garantias(id) ON DELETE CASCADE,
  gateway text NOT NULL,
  external_payment_id text NOT NULL,
  external_reference text NOT NULL UNIQUE,
  qr_code_pix text NULL,
  copia_cola_pix text NULL,
  url_fatura text NULL,
  valor numeric(12,2) NOT NULL CHECK (valor > 0),
  status_gateway text NULL,
  ativa boolean NOT NULL DEFAULT true,
  tentativa integer NOT NULL DEFAULT 1,
  raw_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (gateway, external_payment_id)
);
CREATE UNIQUE INDEX uq_caucao_tentativa
  ON public.caucao_cobrancas (garantia_id, tentativa);
CREATE UNIQUE INDEX uq_caucao_cobranca_ativa
  ON public.caucao_cobrancas (garantia_id) WHERE ativa;
CREATE INDEX idx_caucao_cobrancas_ativa
  ON public.caucao_cobrancas (ativa, garantia_id);

CREATE TABLE public.cliente_documentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN (
    'CPF','COMPROVANTE_RENDA','SEGUNDO_TITULAR',
    'COMPROVANTE_RESIDENCIA_ANTERIOR','OUTRO'
  )),
  nome_arquivo text NOT NULL,
  s3_key text NOT NULL UNIQUE,
  content_type text NOT NULL,
  tamanho_bytes bigint NULL CHECK (
    tamanho_bytes IS NULL OR tamanho_bytes BETWEEN 1 AND 10485760
  ),
  status text NOT NULL DEFAULT 'PENDENTE' CHECK (
    status IN ('PENDENTE','EM_ANALISE','APROVADO','REPROVADO')
  ),
  observacao_analise text NULL,
  enviado_por bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  analisado_por bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  analisado_em timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_cliente_documentos_usuario_historico
  ON public.cliente_documentos (usuario_id, tipo, created_at DESC);
CREATE INDEX idx_cliente_documentos_status
  ON public.cliente_documentos (status, created_at);

CREATE TABLE public.notificacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo text NOT NULL,
  titulo text NOT NULL,
  mensagem text NOT NULL,
  referencia_tipo text NULL,
  referencia_id bigint NULL,
  lida_em timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_notificacoes_usuario
  ON public.notificacoes (usuario_id, lida_em, created_at DESC);

CREATE TABLE public.baixas_manuais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id bigint NOT NULL UNIQUE REFERENCES public.parcelas(id) ON DELETE RESTRICT,
  gateway_cobranca_id bigint NOT NULL REFERENCES public.gateway_cobrancas(id) ON DELETE RESTRICT,
  solicitado_por bigint NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  valor_pago numeric(12,2) NOT NULL CHECK (valor_pago > 0),
  data_pagamento date NOT NULL,
  forma_pagamento text NOT NULL CHECK (
    forma_pagamento IN ('PIX','BOLETO','TRANSFERENCIA','DINHEIRO','CARTAO')
  ),
  comprovante_key text NULL,
  status text NOT NULL DEFAULT 'INICIADA' CHECK (
    status IN ('INICIADA','GATEWAY_CANCELADO','CONCLUIDA','FALHA')
  ),
  erro_mensagem text NULL,
  gateway_cancelado_em timestamptz NULL,
  concluida_em timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_baixas_manuais_status
  ON public.baixas_manuais (status, created_at);
